### ISSUE TITLE
Hunter focus resetting to 0 after leveling up

### ISSUE THREAD

**Issue by Stepparno** [ProjectNelth/BugTracker#10]
Description: Every time you level on a hunter your focus resets to 0, however I believe as with other classes it should be reset to 100

Current behaviour: Resets to 0

Expected behaviour: Reset to 100

Links:

**Comment by iRadioactive** [comment]
Hunter focus should not reset at all, but stay unchanged while gaining a level.
Confirmed by hunter leveling video from retail. Keeping issue open.

**Comment by Stepparno** [comment]
Thanks was unsure if it should reset to full but that confirms it, actually should just stay the same <3
