### ISSUE TITLE
Master Shapeshifter

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#100]
Description:
Moonkin Form: increase spell damage by 4%
Caster Form: Increase healing by 4%.

Current behaviour:
Moonkin Form: Damage is not increased
Caster Form: Healing is not increased
![image](https://user-images.githubusercontent.com/58305537/70646095-36a61880-1c14-11ea-8ebc-8a08886fc76f.png)

Expected behaviour:
Moonkin Form: increase spell damage by 4%
Caster Form: Increase healing by 4%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
