### ISSUE TITLE
Opportunity

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#101]
Description:
Increase the damage of backstab, mutilate, garrote, ambush by 10, 20, 30%.
Current behaviour:
Ambush is scaling to 25% damage benefit from this talent rather than scaling to 30% benefit.

![image](https://user-images.githubusercontent.com/58305537/70680865-78ac7a00-1c67-11ea-8903-4b8f457d7edc.png)

Expected behaviour:
Talent should scale to 30% benefit towards ambush.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
