### ISSUE TITLE
Agression

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#103]
Description:
Increase the damage of sinister strike, backstab, and eviscerate by 7, 14, 20%. Damage scaling issues
Current behaviour:
1. Eviscerate seems to add 30 damage with each additional talent point.
2. Backstab scales to 15% damage benefit from with 3 points, rather than 20%.
3. Sinister strike scales to 15% damage benefit with 3 points, rather than 20%.

![image](https://user-images.githubusercontent.com/58305537/70681619-f5405800-1c69-11ea-9c9c-ee8dab4ba48a.png)

Expected behaviour:
Increase the damage of sinister strike, backstab, and eviscerate by 7, 14, 20%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
