### ISSUE TITLE
Glyph of Mortal strike

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#104]
Description:
Increase the damage of mortal strike by 10%.

Current behaviour:
Currently increases damage by slightly less than intended.
The damage of overpower scales from 173% weapon damage to 188% weapon damage with this glyph. This works out to an 8.6% damage benefit. A correct glyph would come out to 190% weapon damage.

Expected behaviour:
Increased damage by 10%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
