### ISSUE TITLE
Glyph of Templar's verdict

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#105]
Description:
Increase the damage of templar's verdict by 15%.

Current behaviour:
Does not increase damage at all.
![image](https://user-images.githubusercontent.com/58305537/70725010-a5917900-1cc9-11ea-8e8e-dc214817ac67.png)

Expected behaviour:
Increase the damage of templar's verdict by 15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
