### ISSUE TITLE
Blazing Light

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#106]
Description:
Increase the damage of exorcism by 10%, 20%.
Current behaviour:
Increases damage of exorcism by 3%, 6%. 
(looks like it's only receiving 30% spell power benefit as specified under sheath of light)
![image](https://user-images.githubusercontent.com/58305537/70725265-12a50e80-1cca-11ea-9e50-6a866c55b9d1.png)

Expected behaviour:
Increase the damage of exorcism by 10%, 20%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
