### ISSUE TITLE
Glyph of Judgement

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#107]
Description:
Increase damage of judgement by 10%.

Current behaviour:
Does not increase damage at all.
![image](https://user-images.githubusercontent.com/58305537/70725418-56981380-1cca-11ea-8f55-4e46796585cd.png)

Expected behaviour:
Increase damage of judgement by 10%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
