### ISSUE TITLE
Glyph of Word of Glory

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#108]
Description:
Increase healing of word of glory by 10%.

Current behaviour:
Increases healing of word of glory by 5%.
![image](https://user-images.githubusercontent.com/58305537/70725732-e5a52b80-1cca-11ea-9a33-b39eb66e3bb8.png)

Expected behaviour:
Increase healing of word of glory by 10%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
