### ISSUE TITLE
Two-Hand Specialization

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#109]
Description:
Increase damage with 2/hand weapons by 25%.

Current behaviour:
Damage is increased by more than 25%.
![image](https://user-images.githubusercontent.com/58305537/70726049-767c0700-1ccb-11ea-822d-c8587bc82c24.png)

Expected behaviour:
Increase damage with 2/hand weapons by 25%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
