### ISSUE TITLE
Hunter Tame pet not working

### ISSUE THREAD

**Issue by Stepparno** [ProjectNelth/BugTracker#11]
Description: Tame pet currently doesn't do anything, channel finishes and the pet isn't tamed, despite not losing attention of the mob

Current behaviour: ^^^^

Expected behaviour: Should tame the mob successfully if you didn't lose the mob's attention

Links:

**Comment by iRadioactive** [comment]
Was not able to reproduce this. Make sure you don't have an active pet when using Tame pet ability.
If the problem persists, please let us know which beast you are trying to tame and make an in-game ticket for GM assistance.

**Comment by Stepparno** [comment]
It seems to have fixed itself, I was struggling to tame mangy wolf's and spiders in elwynn forest, but i think relogging after learning tame pet fixes it, Might just be a bug upon initially learning the skill from the trainer. Sorry for the false report
