### ISSUE TITLE
Walk in the Light

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#110]
Description:
1. Increase paladin's healing by 10%.
2. Increase word of glory by 30%.

Current behaviour:
Currently the two benefits of walk in the light add up to a 40% benefit for word of glory by adding 10% and 30%.
![image](https://user-images.githubusercontent.com/58305537/70727350-885ea980-1ccd-11ea-8e70-76e91931d8aa.png)

Expected behaviour:
The two talents should be coefficients: X * 1.1 * 1.3 = X*1.43

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
