### ISSUE TITLE
Divinity

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#111]
Description:
1. Increase all healing done by 2%, 4%, 6%.
2. Increase all healing received by 2%, 4%, 6%.

Current behaviour:
Talent has no effect at all.
![image](https://user-images.githubusercontent.com/58305537/70729227-cb6e4c00-1cd0-11ea-9817-8bcc5af366a4.png)

Expected behaviour:
1. Increase all healing done by 2%, 4%, 6%.
2. Increase all healing received by 2%, 4%, 6%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
