### ISSUE TITLE
Crusade: Holy Shock

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#112]
Description:
Increase power of holy shock by 10%, 20%, 30%.
Current behaviour:
Increases power of holy shock up to 25%.
![image](https://user-images.githubusercontent.com/58305537/70730106-60be1000-1cd2-11ea-96c1-4c5a4fe5c219.png)

Expected behaviour:
Increase power of holy shock by 10%, 20%, 30%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
