### ISSUE TITLE
Glyph of Seal of Light

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#113]
Description:
While seal of light is active, increase all healing done by 5%.

Current behaviour:
Zero Effect.
![image](https://user-images.githubusercontent.com/58305537/70730629-5bad9080-1cd3-11ea-8c42-47606f600121.png)

Expected behaviour:
While seal of light is active, increase all healing done by 5%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
