### ISSUE TITLE
Eternal Glory

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#114]
Description:
On casting word of glory, a paladin has (15%, 30%) chance to follow it up with eternal glory spell (88676).

Eternal glory will reset the holy power previously consumed by word of glory.
Eternal glory has a 15 second cooldown.

![image](https://user-images.githubusercontent.com/58305537/89374772-4e0da680-d6ba-11ea-9b9f-5af0b4972c25.png)

Currently, eternal glory works through some unnamed mechanic that is renewing the holy power without an ICD.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by PN-Cryptid** [comment]
This ICD is VERY hard to find a reference to. It was missed in all patch notes and wowhead never had comments specifically about this.

 After looking, it's referenced in Tellmewhen's tooltip as well as old guides.

**Comment by therealsmf** [comment]
could not find official patch note of the change. we also have video confirmation from warmane's neltharion and arena tournament of it having no icd.

**Comment by PN-Cryptid** [comment]
https://www.mmo-champion.com/threads/812824-Holy-Paladins-4-0-3/page8
http://www.mmo-champion.com/threads/771869-Holy-4.0.1
https://www.mmo-champion.com/threads/846940-Visual-notification-for-Eternal-Glory-procs
https://authors.curseforge.com/forums/world-of-warcraft/official-addon-threads/general-addons/218762-recount?page=182
https://forum.wowcircle.net/showthread.php?t=531030
https://cata.wowroad.info/?spell=88676

**Comment by therealsmf** [comment]
https://wowwiki.fandom.com/wiki/Patches/4.x
https://cdn.discordapp.com/attachments/650039701193097257/716802931273498704/unknown.png
https://i.imgur.com/99YaFGM.png
https://i.imgur.com/4fDX1oH.png
https://i.imgur.com/BgHcTiM.png
https://i.imgur.com/AyMelhj.png
https://i.imgur.com/0MBjIb2.png
https://i.imgur.com/9ILj1DB.png
https://i.imgur.com/PZsOmGI.png
https://i.imgur.com/MVCtKf2.png
https://www.warmane.com/changelog?expansion=3&id=
https://www.warmane.com/bugtracker/report/34345
https://www.youtube.com/watch?v=WogNCdBRfyU
https://www.youtube.com/watch?v=L4oKDVEqEC8
https://cdn.discordapp.com/attachments/668221727318343700/764961344293961742/unknown.png
