### ISSUE TITLE
Touched by the Light

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#115]
Description:
Increases stamina by 15%.

Current behaviour:
Increases stamina by 20%.
![image](https://user-images.githubusercontent.com/58305537/70733735-e1800a80-1cd8-11ea-9429-1c472cd7aff3.png)

Expected behaviour:
Increases stamina by 15%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
