### ISSUE TITLE
Seals of the Pure

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#116]
Description:
Increase damage of SoJ, SoR, and SoT by 6%, 12%.

Current behaviour:
No changes by this talent.
![image](https://user-images.githubusercontent.com/58305537/70734306-032dc180-1cda-11ea-98c6-2a279b00b7d7.png)

Expected behaviour:
Increase damage of SoJ, SoR, and SoT by 6%, 12%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
