### ISSUE TITLE
Wrath of the Lightbringer

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#117]
Description:
Increase the damage of your crusader strike and judgement abilities by 50%, 100%.

Current behaviour:
Judgement Damage is not increased with any seal by using this talent.
![image](https://user-images.githubusercontent.com/58305537/70736151-b1873600-1cdd-11ea-8b22-1942d63ec2a9.png)

Expected behaviour:
Increase the damage of your crusader strike and judgement abilities by 50%, 100%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
