### ISSUE TITLE
Guarded by the Light

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#118]
Description:
1. Increase self-healing with word of glory by 10%.
2. Convert over-healing with word of glory into an absorb shield.

Current behaviour:
1. This talent does not increase self-heaing with word of glory.
2. The shield generated by overhealing is always applied to the casting paladin even if healing is not directed at themself.
3. The shield generated does not display absorb amount, if any is generated.

Expected behaviour:
1. Increase self-healing with word of glory by 10%.
2. Convert over-healing with word of glory into an absorb shield.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
