### ISSUE TITLE
Glyph of Hammer of the Righteous

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#119]
Description:
Increase damage of hammer of the righteous by 10%.

Current behaviour:
Damage scaling is less than 10%.
![image](https://user-images.githubusercontent.com/58305537/70737869-83a3f080-1ce1-11ea-8a0a-ffb858d01d91.png)

Expected behaviour:
Increase damage of hammer of the righteous by 10%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
value was measured to be way less than 10%. confirmed.

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.
