### ISSUE TITLE
Glyph of Divine Protection

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#120]
Description:
Stack all protection by divine protection into magical protection.

Current behaviour:
![image](https://user-images.githubusercontent.com/58305537/70738187-3c6a2f80-1ce2-11ea-93c3-3ec826cd7421.png)

Expected behaviour:
Stack all protection by divine protection into magical protection.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
only a tooltip bug.
