### ISSUE TITLE
Fel Armor

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#121]
Description:
Surrounds the caster with fel energy, increasing spell power by X and causes you to be healed for 3% of any single-target spell damage you deal. Only one type of Armor spell can be active on the Warlock at any time.
Current behaviour:
1. To begin with, most spells don't cause fel armor heals.
2. For reasons I haven't figured out, fel armor stops healing entirely part-way through combat.

Spells causing fel armor heals:
Drain soul
Seed of Corruption
Fel Flame
Immolate

Expected behaviour:
"causes you to be healed for 3% of any single-target spell damage you deal"

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
every single target spell during testing has indicated a ~0.03 value of healing of the damage it dealt with fel armor active.
