### ISSUE TITLE
Shadow Mastery

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#122]
Description:
Increase shadow damage by 30%.

Current behaviour:
Shadow damage is increased by 17% for some spells,0% by other spells.
![image](https://user-images.githubusercontent.com/58305537/70742664-0cc02500-1cec-11ea-966f-acbad150cce8.png)

Expected behaviour:
Increase shadow damage by 30%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
