### ISSUE TITLE
Improved Corruption

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#123]
Description:
Increase corruption damage by 4%, 8%, 12%.

Current behaviour:
Corruption damage benfit is scaled to 10% rather than 12%.
![image](https://user-images.githubusercontent.com/58305537/70742919-a982c280-1cec-11ea-8f71-72af5052cc59.png)

Expected behaviour:
Increase corruption damage by 4%, 8%, 12%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
confirmed. results gave back 110.56% increase.

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.
