### ISSUE TITLE
Demonic Knowledge

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#124]
Description: 
Increase shadow damage by 15%.
Increase fire damage by 15%.

Current behaviour:
This passive has no effect.
![image](https://user-images.githubusercontent.com/58305537/70746113-4d6f6c80-1cf3-11ea-8b4f-bcc833d267a3.png)

Expected behaviour:
Increase shadow damage by 15%.
Increase fire damage by 15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
