### ISSUE TITLE
Dark Arts

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#125]
Description:
1. Felhunter: Increase shadow bite damage by 5%, 10%, 15%.
2. Imp: Decrease firebolt cast time by .25 s, 0.50s, 0.75s.
3. Felguard: Increase legion strike damage by 5%, 10%, 15%.

Current behaviour:
1. Felhunter damage is increased by 7 per talent point.
2. Imp cast time is decreased by .22, .45, .68s.
3. Felguard damage is increased by 7 per talent point.

![image](https://user-images.githubusercontent.com/58305537/70746667-3a10d100-1cf4-11ea-83fe-219ec855b0ea.png)

Expected behaviour:
1. Felhunter: Increase shadow bite damage by 5%, 10%, 15%.
2. Imp: Decrease firebolt cast time by .25 s, 0.50s, 0.75s.
3. Felguard: Increase legion strike damage by 5%, 10%, 15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
