### ISSUE TITLE
[Spell][Hunter] Toxicology

### ISSUE THREAD

**Issue by DjrrSk** [ProjectNelth/BugTracker#126]
Description:
Increases the periodic critical damage of your Serpent Sting and Black Arrow by 50% (rank 1)  / 100% (rank 2).
Current behaviour:
It just increases by around 17% (rank 1) / 35% (rank 2)
Expected behaviour:
Increases the periodic critical damage of your Serpent Sting and Black Arrow by 50% (rank 1)  / 100% (rank 2).
Links:
https://www.wowhead.com/spell=82833/toxicology
https://imgur.com/a/h5fTuo7

**Comment by therealsmf** [comment]
results            0/2    1/2    2/2

serpent sting        1721    1721    1721
black arrow        1333    1333    1333

serp sting crit        2581    3011    3441
black arrow crit    1999    2332    2665

scaling should be    1.5->1.75->2

and it is. working as intended.
