### ISSUE TITLE
Demonic Pact

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#127]
Description:
1. Increase your spell damage by 2%.
2. your summoned pet produces an aura to increase spell damage by 10% for everyone within 40 yards.

Current behaviour:
1. Does NOT increase the warlock's spell damage by 2%.
2. your summoned pet produces an aura to increase spell damage by 10% for everyone within 40 yards.
Expected behaviour:
1. Increase your spell damage by 2%.
2. your summoned pet produces an aura to increase spell damage by 10% for everyone within 40 yards.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
