### ISSUE TITLE
Improved Rejuvenation

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#128]
Description:
Improve the healing of rejuvenation and swiftmend by 5%, 10%, 15%.

Current behaviour:
Talent seems to scale the two abilities up to 10% rather than 15%.

![image](https://user-images.githubusercontent.com/58305537/70757109-6afd0000-1d0c-11ea-8457-baeadbc455cf.png)

Expected behaviour:
Improve the healing of rejuvenation and swiftmend by 5%, 10%, 15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
~4/8/12 was measured.

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.
