### ISSUE TITLE
Empowered Touch

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#129]
Description:
Increase the direct healing of Healing touch, regrowth, and nourish by 5%, 10%.

Current behaviour:
Currently scales the abilities up to 7% instead of 10% extra healing.

![image](https://user-images.githubusercontent.com/58305537/70757386-5ff69f80-1d0d-11ea-8818-6d48d14c62de.png)

Expected behaviour:
Increase the direct healing of Healing touch, regrowth, and nourish by 5%, 10%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
