### ISSUE TITLE
Glyph of Rejuvenation

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#130]
Description:
Increase the power of rejuvenation by 10%.

Current behaviour:
Only increases the power of rejuvenation by 7%.
![image](https://user-images.githubusercontent.com/58305537/70757631-4bff6d80-1d0e-11ea-9db1-18dbb6ab98a8.png)

Expected behaviour:
Increase the power of rejuvenation by 10%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
6.96% was measured. confirmed.

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.
