### ISSUE TITLE
Cataclysm (Destruction Passive) + Fiery Apocalypse (Destruction Mastery)

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#131]
Description:
Increase fire damage by 25%.
Increase fire damage by X%.

Current behaviour:
These passives has no effect on warlock spells.
![image](https://user-images.githubusercontent.com/58305537/70758598-8ae2f280-1d11-11ea-9349-0dfc745051c5.png)

Expected behaviour:
Increase fire damage by 25%.
Increase fire damage by X%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
Incinerate doesn't seem to be affected by mastery. Everything else showed a damage increase of around 137%. Created a new report for that one spell alone.
