### ISSUE TITLE
Cloak of Shadows

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#132]
Description:
Removes and provides immunity from harmful magic effects.

Current behaviour:
A death knight can apply frost fever to a cloaked rogue via chains of ice.

![image](https://user-images.githubusercontent.com/58305537/70759742-5cffad00-1d15-11ea-8c45-beb8b2e8ea04.png)

Expected behaviour:
A rogue should be totally immune to harmful magic debuffs.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
