### ISSUE TITLE
Glyph of imp

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#133]
Description:
Increase your imp's firebolt damage by 20%.

Current behaviour:
Damage is increased by roughly 1%.
![image](https://user-images.githubusercontent.com/58305537/70760824-f1b7da00-1d18-11ea-9cd5-2d0eee000b08.png)

Expected behaviour:
Increase your imp's firebolt damage by 20%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
