### ISSUE TITLE
Glyph of Lash of Pain

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#134]
Description:
Increase your succubus's lash of pain damage by 25%.

Current behaviour:
Damage is increased by 2.5%.
![image](https://user-images.githubusercontent.com/58305537/70760928-5bd07f00-1d19-11ea-89a3-fe8a4f00d2c4.png)

Expected behaviour:
Increase your succubus's lash of pain damage by 25%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
