### ISSUE TITLE
Glyph of Felguard

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#135]
Description:
Increase your felguard's legion strike damage by 5%.

Current behaviour:
Damage is not increased by any significant amount.

![image](https://user-images.githubusercontent.com/58305537/70761060-ea450080-1d19-11ea-9922-663c806c0b1c.png)

Expected behaviour:
Increase your felguard's legion strike damage by 5%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
