### ISSUE TITLE
Druid Forms Speed

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#136]
Description:
Druid forms currently have incorrect and awkward movement speeds.

Current behaviour:
![image](https://user-images.githubusercontent.com/58305537/70802475-8c4b0400-1d7f-11ea-9160-173605cd8ca2.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/58305537/70802697-1abf8580-1d80-11ea-9037-2cc015db8b4d.png)

EDIT: Had a mistake where I did not display the foot enchant stacking.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by PN-Cryptid** [comment]
Corrected in recent months, closing.
