### ISSUE TITLE
Drowning

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#137]
Description:
kills a player if the player is under the surface of water for too long.

Current behaviour:
Drowning will kill a player idle at the surface of water.
My guess by just looking at it is that the game is keeping players deeper than the actual surface when trying to swim up.

![image](https://user-images.githubusercontent.com/58305537/70802986-fc0dbe80-1d80-11ea-8db9-6531642251e0.png)

Expected behaviour:
Drowning should not occur to players who are at the surface level of water.
-Characters should be able to swim with their head above water.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
