### ISSUE TITLE
Aggression (Feral Passive)

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#138]
Description:
Increase attack power by 25%.

Current behaviour:
Attack power is increased by 30%.
![image](https://user-images.githubusercontent.com/58305537/70803631-81de3980-1d82-11ea-96ea-71bb14c20bcc.png)

Expected behaviour:
Increase attack power by 25%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
