### ISSUE TITLE
Razor Claws (Feral Mastery)

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#139]
Description:
Increase damage of bleed abilities by X%.

Current behaviour:
When learned, this coefficient does not apply properly to all of the bleed spells. 

Even without the attack power increase, this ability would increase the damage of bleed abilities by 37% based on my current mastery. The grey bar is the change factor. The green numbers are the hypothetical numbers if increased by 30% attack power (bugged) and then 37% from mastery.

![image](https://user-images.githubusercontent.com/58305537/70806392-34b19600-1d89-11ea-9102-e94c58418148.png)

Expected behaviour:
Increase damage of bleed abilities by X%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
