### ISSUE TITLE
Thick Hide

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#140]
Description:
1. Increase base armor by 4, 7, 10%.
2. Increase bear form multiplier by 26%, 52%, 78%. (220% to 298%)

Current behaviour:
1. base armor increase works properly.
2. Bear form multiplier is increasing by 57% per talent point instead of 26%.

![image](https://user-images.githubusercontent.com/58305537/70809186-426a1a00-1d8f-11ea-9724-7ee472056765.png)

Expected behaviour:
1. Increase base armor by 4, 7, 10%.
2. Increase bear form multiplier by 26%, 52%, 78%. (220% to 298%)

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by PN-Cryptid** [comment]
So for the record, this talent is actually a mechanical fluke.
Thick hide is given the tooltip definition of an additive mechanic similar to glyph of divine plea and glyph of shield wall, but blizzard's thick hide did not abide by that calculation for this talent.

https://www.youtube.com/watch?v=vzzcG9Dl8bw

For us, this was the deciding video where it showed a 380 feral tank in line with the armor value of a multiplicative calculation rather than an additive calculation.

Multiplicative: 1x armor + (1.2 * 1.76)x armor
Additive: 1x armor + (1.2+.76)x armor
The difference in these calculations would have been roughly 12k armor at full BIS in 4.3.4.
