### ISSUE TITLE
Heart of the Wild

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#141]
Description:
1. Increase intellect by 2, 4, 6%.
2. Bear form: Increase stamina by 2, 4, 6%.
3. Cat Form: Increase attack power by 4, 7, 10%.

Current behaviour:
1. Increase intellect by 7, 9, 11%.
2. Bear form: Increase stamina by 6% with first talent point, no benefit to second or third.
3. Cat Form: Increase attack power by 10% with first talent point, no benefit to second or third.
![image](https://user-images.githubusercontent.com/58305537/70813288-3f732780-1d97-11ea-86fc-55480ac3a1ec.png)

Expected behaviour:
1. Increase intellect by 2, 4, 6%.
2. Bear form: Increase stamina by 2, 4, 6%.
3. Cat Form: Increase attack power by 4, 7, 10%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
