### ISSUE TITLE
Glyph of Rip

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#142]
Description:
Increase damage of rip by 15%.

Current behaviour:
Increases damage of rip by 1%.
![image](https://user-images.githubusercontent.com/58305537/70813832-27e86e80-1d98-11ea-9393-d74adbca3aeb.png)

Expected behaviour:
Increase damage of rip by 15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
