### ISSUE TITLE
Sentinel

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#143]
Description:
Increase stamina by 15%.
Increase Block chance by 15%.
-Additional Rage

Current behaviour:
Stamina is increased by 20%.
Block chance is increased properly.
![image](https://user-images.githubusercontent.com/58305537/70824158-9553c980-1daf-11ea-9512-4d4cb51b5047.png)

Expected behaviour:
Increase stamina by 15%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
plate spec didnt apply without talents. the 1.0275 is 1.15 (sentinel) * 1.05 (plate spec).
