### ISSUE TITLE
Souldrinker HC

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#144]
Description:
Souldrinker Proc:
Damage your target for 1.7% of your own health.
Heal yourself for double the damage dealt.

Current behaviour:
Damage scales properly.
Heals yourself for only 2, regardless of health status.
![image](https://user-images.githubusercontent.com/58305537/70824910-3db65d80-1db1-11ea-88b8-d667f085e243.png)

Expected behaviour:
Damage your target for 1.7% of your own health.
Heal yourself for double the damage dealt.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
overkills don't count. results show the correct healing amount if target has more hp than 1.7% of player.
