### ISSUE TITLE
Thunderstruck

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#145]
Description:
Increase the damage of Rend, cleave, and thunderclap by 3%, 6%.

Current behaviour:
Rend and cleave are not affected by this talent.
![image](https://user-images.githubusercontent.com/58305537/70826531-2aa58c80-1db5-11ea-9623-32498fb5b071.png)

Expected behaviour:
Increase the damage of Rend, cleave, and thunderclap by 3%, 6%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
