### ISSUE TITLE
Glyph of Revenge

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#146]
Description:
Increase damage of revenge by 10%

Current behaviour:
Damage is increased by less than 10%.
![image](https://user-images.githubusercontent.com/58305537/70827155-a7853600-1db6-11ea-960d-dce1c046f0c7.png)

Expected behaviour:
Increase damage of revenge by 10%

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
