### ISSUE TITLE
War Academy: Bloodthirst

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#148]
Description:
Increase the damage of bloodthirst by 5%, 10%, 15%.

Current behaviour:
This talent has no effect on bloodthirst.

Expected behaviour:
Increase the damage of bloodthirst by 5%, 10%, 15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
war academy does not boost bloodthirst damage. only mortal strike / raging blow / devastate / victory rush / slam are affected.
