### ISSUE TITLE
No'Kaled, the elements of death

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#149]
Description:
Melee hits have a chance to blast the target for 10800 (random spell type) damage.

Current behaviour:
Triggered by ranged attacks such as throw and deadly throw.

![image](https://user-images.githubusercontent.com/58305537/70840420-1cb93100-1de0-11ea-8b16-8caf3af987e4.png)

Expected behaviour:
Unlike vial, this proc should only be triggered by melee attacks.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
