### ISSUE TITLE
Vitality

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#150]
Description:
Increase energy regeneration by 25%, and attack power by 30%.

Current behaviour:
Attack power is increased by 36%.
![image](https://user-images.githubusercontent.com/58305537/70840597-53dc1200-1de1-11ea-9a73-50312763db93.png)

Expected behaviour:
Increase energy regeneration by 25%, and attack power by 30%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
