### ISSUE TITLE
Assassin's Resolve

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#151]
Description:
While wielding daggers, your damage is increased by 20%, and total energy increased by 20.
-Only active if dual wielding daggers.

Current behaviour:
1. Damage is increased by over 20%.
2. The passive is not dependent on dual wielding or even single-wielding daggers. You can get this bonus with double axes.

![image](https://user-images.githubusercontent.com/58305537/70841918-732c6c80-1dec-11ea-9198-78b2edfa92fe.png)

Expected behaviour:
While wielding daggers, your damage is increased by 20%, and total energy increased by 20.
-Only active if dual wielding daggers.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
20 energy is gained regardless of weapons. couldn't reprocude damage bonus without daggers in both hands.
