### ISSUE TITLE
Mastery: Potent Poisons (Assassination)

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#152]
Description:
Increase damage by poisons by X%.

Current behaviour:
Mastery for Assassination rogue seems to be overscaling slightly.
![image](https://user-images.githubusercontent.com/58305537/70842253-4ded2d80-1def-11ea-9492-cb2714a0abfd.png)

Expected behaviour:
Increase damage by poisons by X%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
