### ISSUE TITLE
Vile Poisons

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#153]
Description:
Increase the damage of your poisons by 12%, 24%, 36%.

Current behaviour:
This talent is under-scaling poison damage, increasing by 22% instead of 36%.
![image](https://user-images.githubusercontent.com/58305537/70842288-b3411e80-1def-11ea-81f4-6f32e797a586.png)

Expected behaviour:
Increase the damage of your poisons by 12%, 24%, 36%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
115.27% / 117.78% / 126.67% were tested. confirmed underpowered.

**Comment by therealsmf** [comment]
testing again on a brand new fresh character, naked, without mastery or any other talent interference:

scaling should be: 1 -> 1.12 -> 1.24 -> 1.36

results (25 sample size):
0/3  1/3  2/3  3/3
423 474 525 575
1 1.1205 1.2411 1.3593

looks accurate enough to me, probably the initial test results were affected by other talents/mastery/etc.
