### ISSUE TITLE
Frost Specialization

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#154]
Description:
Increase the damage of frostbolt by 40%.
Increase the damage of frost spells other than frost bolt by 25%.

Current behaviour:
the "extra" 15% appears to be applied to frostbolt properly.
The blanket 25% buff is not applied to any frost or frostfire spells.

![image](https://user-images.githubusercontent.com/58305537/70842991-cefcf280-1df8-11ea-9dd1-c53bf25b1a96.png)

Expected behaviour:
Increase the damage of frostbolt by 40%.
Increase the damage of frost spells other than frost bolt by 25%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
