### ISSUE TITLE
Fire Specialization

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#155]
Description:
Increase damage of fire damage spells by 25%.

Current behaviour:
This passive has no effect.
![image](https://user-images.githubusercontent.com/58305537/70850183-77d93b00-1e55-11ea-9f3e-14df4e49ab6f.png)

Expected behaviour:
Increase damage of fire damage spells by 25%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
check reports 248 and 249. everything else is working properly.
