### ISSUE TITLE
Fire Power

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#156]
Description:
Increase fire damage by 1%, 2%, 3%.

Current behaviour:
This passive has no effect.
![image](https://user-images.githubusercontent.com/58305537/70850320-e36fd800-1e56-11ea-8ed2-a4fb93f886f4.png)

Expected behaviour:
Increase fire damage by 1%, 2%, 3%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
report 250, everything else is fine
