### ISSUE TITLE
Arcane Tactics

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#158]
Description:
Increase raid members' damage within 40 yards damage by 3%.

Current behaviour:
This talent does not increase damage.
![image](https://user-images.githubusercontent.com/58305537/70850883-1e750a00-1e5d-11ea-990d-6f4893aba909.png)

Expected behaviour:
Increase raid members' damage within 40 yards damage by 3%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by PN-Cryptid** [comment]
The damage increase is actually present.
