### ISSUE TITLE
Arcane Specialization

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#159]
Description:
Increase arcane damage by 25%.

Current behaviour:
This passive has no effect.
![image](https://user-images.githubusercontent.com/58305537/70850935-ca1e5a00-1e5d-11ea-8cc3-2b39fb043b26.png)

Expected behaviour:
Increase arcane damage by 25%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
