### ISSUE TITLE
Quest: Disrupt Their Reinforcements

### ISSUE THREAD

**Issue by omegaroll** [ProjectNelth/BugTracker#16]
Description: You need Demonic Rune Stone which drop from mobs to disrupt 2 ports. I got the Demonic Rune Stone's, but when I try to disrupt the ports it says "you have no target".

Current behaviour: After you collected 4 Demonic Rune Stone's and try to Disrupt Port Xilus or Port Kruul, it says "you have no target".

Expected behaviour: You should be able to Disrupt the Ports when you have 4 Demonic Rune Stone's in your bag. After you casted "Detonating Rune Stones" it should complete the Disrupt.

Links:
https://www.wowhead.com/quest=10208/disrupt-their-reinforcements
https://www.youtube.com/watch?v=LM83K5KNWxk

**Comment by iRadioactive** [comment]
Quest will autocomplete now. Will get back to this.
