### ISSUE TITLE
Twin Discipline

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#160]
Description:
1. Increase all healing by 2, 4, 6%.
2. Increase all damage by 2,4, 6%.

Current behaviour:
1. Only Power Word: Shield and Prayer of Mending are affected by twin discipline's healing bonus.
Spells missing: Penance, divine hymn, flash heal, greater heal, heal, holy nova, prayer of healing, renew.
2. No increase in damage by this passive.

![image](https://user-images.githubusercontent.com/58305537/70853058-e1b60c80-1e76-11ea-8c95-5dac80a38c36.png)

Expected behaviour:
1. Increase all healing by 2, 4, 6%.
2. Increase all damage by 2,4, 6%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
twin disciplines DOES scale shadow damage properly. holy damage is significantly underpowered - 1/3 and 2/3 yield even lower results than 0/3, and 3/3 is a 1% upgrade over 0/3. holy nova healing is OP. sanctuary is wrong at 3/3 - healing is less than at 2/3. greater heal does not scale properly. 1/3 over 0/3 barely noticable, 2/3 should be 1/3, 3/3 should be 2/3, 3/3 should be 1.06x 0/3 value.

**Comment by therealsmf** [comment]
scaling should be 1->1.02->1.04->1.06. removed results that yielded correct amounts.

current results	0/3	1/3	2/3	3/3

chastise	1	0.97	0.99	1.01
holy fire	1	0.99	0.99	1.04
holy fire dot	1	0.98	0.99	1.01
smite		1	0.97	0.99	1.01
nova dmg	1	0.97	0.99	1.01

nova heal	1	1.07	1.11	1.15

sanc		1	1.02	1.04	1.0365
great		1	1.005	1.022	1.044

**Comment by therealsmf** [comment]
![image](https://user-images.githubusercontent.com/66882878/130696804-db037c65-07f4-4345-907f-64cd6b834438.png)

**Comment by therealsmf** [comment]
its possible that the bonus 15% aoe healing buff from chakra gets applied before this talent.
in that case it would still be slightly off, correct values would need to yield results of 
1 -> 1.17/1.15 = 1.01739 -> 1.19/1.15 = 1.03478 -> 1.21/1.15 -> 1.05217

**Comment by therealsmf** [comment]
tested again without any other talent interference:
results should be 1->1.02->1.04->1.06

sample size: average ticks from 3 full casts, excluding crits

0/3        1/3       2/3        3/3
2001    2042     2081     2123
1      1.02049 1.03998 1.06097

after recent changes it seems to be a lot more accurate, probably because of the global fix for stacking talents/spells. sample size is too low to get even more precise results, so id consider this fixed
