### ISSUE TITLE
Empowered Healing

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#161]
Description:
Increase the healing of heal, flash heal, binding heal, greater heal by 5,10,15%.

Current behaviour:
Talent is scaling to 13% benefit rather than 15% benefit.
![image](https://user-images.githubusercontent.com/58305537/70853787-e253a080-1e80-11ea-9d8f-d0956f0d7895.png)

Expected behaviour:
Increase the healing of heal, flash heal, binding heal, greater heal by 5,10,15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
results		0/3	1/3	2/3	3/3

flash heal	17888	18673	19405	20042
reg. heal	8959	9313	9668	10061
greater heal	23755	24906	25819	26769		
binding heal	13818	14219	15106	15470

simplified

flash heal	1	1.044	1.085	1.120
reg. heal	1	1.040	1.079	1.123
greater heal	1	1.048	1.087	1.127
binding heal	1	1.029	1.093	1.120

conclusion

talent is underpowered for every point for every spell. scaling should be 1->1.05->1.1->1.15 (underpowered by 2-3%.)

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.
