### ISSUE TITLE
Improved Renew

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#162]
Description:
Increase the healing by renew by 5%, 10%.

Current behaviour:
Talent is scaling renew's bonus healing slightly lower than 10%.
![image](https://user-images.githubusercontent.com/58305537/70853841-66a62380-1e81-11ea-9a38-94bd2ef5c686.png)

Expected behaviour:
Increase the healing by renew by 5%, 10%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
improved renew - increases amount by 5/10%.

results		0/2	1/2	2/2

renew tick	3010	3141	3272

simplified	1	1.044	1.087

confirmed underpowered.

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.
