### ISSUE TITLE
Heavenly Voice

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#163]
Description:
Increase the healing by divine hymn by 50, 100%.

Current behaviour:
Currently only increasing healing by 87%.
![image](https://user-images.githubusercontent.com/58305537/70853955-2ba4ef80-1e83-11ea-9f02-522074501bd5.png)

Expected behaviour:
Increase the healing by divine hymn by 50, 100%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
heavenly voice - increases divine hymn healing by 50/100%.

results		0/2	1/2	2/2

divine hymn	9861	14148	18436

simplified	1	1.435	1.870

confirmed underpowered.

**Comment by therealsmf** [comment]
HEAL_PER_TICK = (4009 + %SP * .429) * (1 + %SH + %SANC + %HV) * (1 + %TD)
%SP = Spell Power
%SH = Spiritual Healing
%SANC = Chakra: Sanctuary
%HV = Heavenly Voice
%TD = Twin Disciplines

With all the above talents, the formula is:

HEAL_PER_TICK = (4009 + %SP * .429) * (1 + .15 + .15 + 1) * (1 + .06)

with the same setup before and after, the test was done without a chakra. as the after/before division can be simplified to the values in the 2nd parentheses, the test results are just 1.65/1.15  at 1 point and 2.15/1.15 at 2.

the talent is working as intended.

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.

**Comment by PN-Cryptid** [comment]
This report is among others with a common source of error yet to be found:
119, 123, 128, 130, 161, 162, 163.
