### ISSUE TITLE
Shadow Power

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#164]
Description:
Increase spell damage by 15%.
Increase crit bonus from 50% to 100%.

Current behaviour:
Critical strike bonuses are correctly increased from 50% to 100%.
No spells benefit from the spell damage increase.

![image](https://user-images.githubusercontent.com/58305537/70854246-0dd98980-1e87-11ea-9266-7d1ac5ab3a55.png)

Expected behaviour:
Increase spell damage by 15%.
Increase crit bonus from 50% to 100%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
before

dp 1871 ticks, 2889 crit

after

dp 2151 ticks, 4493 crit

conclusion -> working as intended.
