### ISSUE TITLE
Darkness

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#165]
Description:
Increase haste by 1%, 2%, 3%.

Current behaviour:
Haste increase is 1.2% per talent point.
![image](https://user-images.githubusercontent.com/58305537/70854332-3910a880-1e88-11ea-9c32-1d9be9b57da0.png)

Expected behaviour:
Increase haste by 1%, 2%, 3%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
darkness - increases haste by 1/2/3%.

results

haste	0/3	1/3	2/3	3/3

3093	24.15%	25.39%	26.64%	27.88%

conclusion:

haste has multiple components. there is a difference between haste rating and haste percentage. the percentage is not only based on your gear alone. your total haste is a combination of rating and percentage values. the talent boosts the gain from rating and gives a passive percentage bonus to the total value.

the formula is:

haste rating (from gear) * 1.01/1.02/1.03 + 1.01/1.02/1.03

so, with 3093 haste from gear, it should be

24.15 * 1.01 + 1 = 25.3915
24.15 * 1.02 + 2 = 26.633
24.15 * 1.03 + 3 = 27.8745

and it is. the talent is working as intended.
