### ISSUE TITLE
Twisted Faith

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#166]
Description:
Increase shadow damage by 1%, 2%.
Grant Hit rating equal to 50%, 100% spirit.

Current behaviour:
Spirit is properly copied to hit rating.
Shadow damage is not increased.
![image](https://user-images.githubusercontent.com/58305537/70854416-6ca00280-1e89-11ea-8995-fce4f8e4bf0d.png)

Expected behaviour:
Increase shadow damage by 1%, 2%.
Grant Hit rating equal to 50%, 100% spirit.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
twisted faith - increase shadow spell dmg by 1/2%.

results		0/2	1/2	2/2

sear		3493	3532	3573
pain		2325	2349	2372
flay		3739	3777	3814
imp dp	5807	5867	5923
dp		2151	2173	2194
death	4255	4297	4340
vt		4418	4462	4506

simplified

sear		1	1.011	1.023
pain		1	1.010	1.020
flay		1	1.010	1.020
imp dp	1	1.010	1.020
dp		1	1.010	1.020
death	1	1.010	1.020
vt		1	1.010	1.020


conclusion: working as intended.
