### ISSUE TITLE
Improved Devouring Plague

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#167]
Description:
Instantly deal 15%, 30% of devouring plague's total damage instantly when applied.

Current behaviour:
The scaling is slightly over 15%, 30%.
![image](https://user-images.githubusercontent.com/58305537/70854547-5abf5f00-1e8b-11ea-82be-5232d27650f9.png)

Expected behaviour:
Instantly deal 15%, 30% of devouring plague's total damage instantly when applied.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
