### ISSUE TITLE
Shadow Form

### ISSUE THREAD

**Issue by cryptid123** [ProjectNelth/BugTracker#168]
Description:
Increase all shadow damage by 15%.

Current behaviour:
Only Shadow word: pain benefits from shadow form.
![image](https://user-images.githubusercontent.com/58305537/70854620-1bddd900-1e8c-11ea-8202-65addf213e6f.png)

Expected behaviour:
Increase all shadow damage by 15%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by iRadioactive** [comment]
Shadowform seems to increase shadow damage correctly on newest updated core.
