### ISSUE TITLE
Devouring Plague

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#169]
Description:
Deal X damage to the target over X seconds.
Heals the caster for 15% of the damage caused by devouring plague.

Current behaviour:
15% Self-Healing is only activated by "improved devouring plague", the instant portion of damage.
DOT damage does NOT heal the caster 15%.

Expected behaviour:
Instant and DOT damage should both heal the priest.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
