### ISSUE TITLE
Vampiric Embrace

### ISSUE THREAD

**Issue by cryptid123** [ProjectNelth/BugTracker#170]
Description:
Causes your single-target damage to heal you for 6% and your raid/party for 3% of damage done.

Current behaviour:
Zero healing is generated.

Expected behaviour:
Causes your single-target damage to heal you for 6% and your raid/party for 3% of damage done.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by Goztoc** [comment]
Vampiric Embrace works as intended. Make sure you're in party/raid.
