### ISSUE TITLE
Pet Pathing

### ISSUE THREAD

**Issue by Refurinn** [ProjectNelth/BugTracker#171]
Description: Pets in combat tends to just walk around alot trying to get to the enemies rather than going in a straight line to them.

Current behaviour: Walking back and forth trying to get to enemies when fighting them in the move, Also walking through locked doors and walls to pull bosses / monsters locked inside.

Expected behaviour: Taking the shortest path to the enemies and not being stuck in a loop when moving to enemies. Also hitting walls rather than going through them.

Links:

**Comment by PN-Cryptid** [comment]
Pet pathing has since been greatly improved.

**Comment by therealsmf** [comment]
merged with other pet related issues at https://forum.projectnelth.com/bugtracker/pet-spells-autocasts-r75/
