### ISSUE TITLE
Purification

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#174]
Description:
Resto shaman passive:
1. Increase all healing by 25%.
2. decrease cast time of healing wave and greater healing wave by 0.5s.

Current behaviour:
1. earth shield and healing stream totem are not receiving a benefit from purification properly.
2. works fine.
![image](https://user-images.githubusercontent.com/58305537/70865542-d9200d80-1f2c-11ea-9715-0e10f1724b0d.png)

Expected behaviour:
Resto shaman passive:
1. Increase all healing by 25%.
2. decrease cast time of healing wave and greater healing wave by 0.5s.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
confirmed underpowered. healing stream only gets a 10% buff instead of 25%.
