### ISSUE TITLE
Spark of Life

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#175]
Description:
Increase healing done by 6%.
Increase healing taken by 15%.

Current behaviour:
Spells are slightly over-scaling to 25% self-healing with 3/3 spark of life.
The correct coefficient is 1.15*1.06 = 1.22

This data is based off the average of 500 self-casts of each spell with each talent progress.

![image](https://user-images.githubusercontent.com/58305537/70866589-9ca6de80-1f39-11ea-8ec7-97c29aeb178f.png)

Expected behaviour:
The correct coefficient is 1.15*1.06 = 1.22

**Comment by therealsmf** [comment]
spark of life - increases healing done and received by 2% 5%, 4% 10%, 6% 15%.

if im healing myself, scaling should be 1->1.071->1.144->1.219.

results		0/3	1/3	2/3	3/3

chain		7717	8055	8642	9175
earth shield	2621	2717	2902	3093
unleash		4439	4779	5069	5399
ghw		21056	22540	23603	25269
rain		1679	1731	1861	1986
totem		685	719	753	787
surge		10668	11057	11807	12561
wave		6663	6942	7409	7885
riptide		2483	2578	2755	2935

simplified

chain		1	1.044	1.120	1.189
earth shield	1	1.037	1.107	1.180
unleash		1	1.077	1.142	1.216
ghw		1	1.070	1.121	1.200
rain		1	1.031	1.108	1.183
totem		1	1.050	1.099	1.149
surge		1	1.036	1.107	1.177
wave		1	1.042	1.112	1.183
riptide		1	1.038	1.110	1.182

conclusion: everything (except unleash life) is about 97% of what it should be.

**Comment by therealsmf** [comment]
same category as heavenly voice - missed on initial scan
