### ISSUE TITLE
Frozen Heart

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#177]
Description:
Frost DK Mastery:
Increase frost damage by x%.

Current behaviour:
Mastery has no effect on frost damage values.

Expected behaviour:
Frost DK Mastery:
Increase frost damage by x%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
frozen heart - increases damage by mastery. (34%)

results		before	after

frost strike	7309	9788
howling blast	4479	6001
icy touch	1966	2631
obliterate	5750	6319
frost fever	480	643

simplified

frost strike	1	1.339
howling blast	1	1.340
icy touch	1	1.338
frost fever	1	1.340

conclusion: working as intended.
