### ISSUE TITLE
ashenvale quests and npcs start area

### ISSUE THREAD

**Issue by ffdevill** [ProjectNelth/BugTracker#180]
Description: the whole Ashenvale start area is spawned wrong and the quests are all set up wrong or are outright missing this is a known issue with trinity core for this xpac usually it is the prereq quests are set wrong none of the quests there should have prereq just a fyi but the npcs that are all spawned dead should be alive

**Comment by PN-Cryptid** [comment]
This area has been cleaned up, but remains without PN scripting.
