### ISSUE TITLE
Shamanism

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#182]
Description:
Increase your benefit from spell power by 36%.

Current behaviour:
Spell power in increased by 336. (?)

It seems as though the damage scaling of spells is increased by roughly 55%.
I Isolated the effect of just the trinkets and I don't see any resemblance to a 36% increase.

![image](https://user-images.githubusercontent.com/58305537/71001229-d64b2700-20aa-11ea-9ffe-da61bf468bec.png)

Expected behaviour:
Increase your benefit from spell power by 36%.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
results		before	after

lightning bolt	5932	8538
chain lightning	5223	7825
lava burst	6142	8727

simplified

lightning bolt	1	1.439
chain lightning	1	1.498
lava burst	1	1.421

conclusion: every spell benefits from spell power differently. as every damage value tested gets more than a 36% buff in damage, we can safely assume they are working as intended.
