### ISSUE TITLE
Concussion

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#183]
Description:
Increase damage of certain spells by 2%, 4%, 6%.

Current behaviour:
Flame shock and earth shock are receiving extra benefit from this talent.
![image](https://user-images.githubusercontent.com/58305537/71005944-8708f480-20b2-11ea-8ce5-452c58482e1d.png)
Note: Frost shock had a roughly normal benefit.

Expected behaviour:
Increase damage of certain spells by 2%, 4%, 6%.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
concussion - increases damage of certain spells by 2/4/6%

potential problem: earth shock and flame shock are overtuned.

results			0/3	1/3	2/3	3/3

earth shock		4494	4581	4674	4764
flame shock initial	2505	2555	2605	2655
flame shock dot		1065	1086	1107	1128

simplified (should be 1->1.02->1.04->1.06)

earth shock		1	1.019	1.040	1.060
flame shock initial	1	1.020	1.040	1.060
flame shock dot		1	1.020	1.039	1.059

conclusion: report is invalid.
