### ISSUE TITLE
Elemental Reach

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#185]
Description:
Increase range of fire nova by 10 yards.

Current behaviour:
Fire nova's range is not increased by 10 yards as the talent suggests.
![image](https://user-images.githubusercontent.com/58305537/71033741-ed5b3a80-20e5-11ea-990c-06603557613e.png)

Expected behaviour:
Increase range of fire nova by 10 yards.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by PN-Cryptid** [comment]
fixed.
