### ISSUE TITLE
Earth's grasp

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#189]
Description:
give your earthbind totem a 50%, 100% chance to root nearby targets.

Current behaviour:
There seems to be no diminishing returns to this effect. It does not trigger a diminishing return on itself.

Expected behaviour:
This talent should be on the "controlled root" DR.

Links:
https://wowwiki.fandom.com/wiki/Diminishing_returns

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by PN-Cryptid** [comment]
Confirmed recently, marked for fix in an old list sent to devs.
