### ISSUE TITLE
Coiled Ropes in Southern Barrens

### ISSUE THREAD

**Issue by Sardean** [ProjectNelth/BugTracker#19]
Description:
Coiled ropes in Southern Barrens located in Honor's Stand that are used for horde to climb mountains do not work.
Current behaviour:
Does nothing.
Expected behaviour:
Should pull you to the next rope in order to climb mountain side.
Links:

**Comment by therealsmf** [comment]
should be reported in the big zone reports on the questing spreadsheet. if the issue still exists after changes, reopen on the forum :)
