### ISSUE TITLE
Mental Quickness

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#190]
Description:
Decrease the mana cost of your instant beneficial, instant damaging, and totem spells.

Current Behavior:
1. Does not affect primal strike's mana cost
2. Does not affect lava lash's mana cost.

![image](https://user-images.githubusercontent.com/58305537/71082058-701fdc00-215e-11ea-8dc3-e6fa56ed7eb4.png)

**Comment by cryptid123** [comment]
This report is based off of examined numbers, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
lava lash comes in the "same package" as mental quickness (specing enh). stormstrike replaces primal strike, which is accessed in the same tree that mental quickness benefits. theres no way/no reason to reproduce that would affect gameplay.
