### ISSUE TITLE
Improved lava lash

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#193]
Description:
Increase the damage of your lava lash by 20% per stack of searing flames on the target.

Current behaviour:
Damage bonus seems to be scaling to 70% additional effect, lower than intended.
![image](https://user-images.githubusercontent.com/58305537/71097807-9d7c8200-217e-11ea-95f1-b47147488b57.png)

Expected behaviour:
Increase the damage of your lava lash by 20% per stack of searing flames on the target.

**Comment by cryptid123** [comment]
This report is based off of examined numbers, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
results		0/2	1/2	2/2

lava lash	2776	4173	5492

		1	1.503	1.978

conclusion: working as intended.
