### ISSUE TITLE
static shock

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#194]
Description:
Gives your primal strike, stormstrike, and lava lash a 15%, 30%, 45% chance to proc a lightening shield attack when casted.

Current behaviour:
Stormstrike is getting double proc chance, likely because it is proccing off of stormstrike off-hand as well.

![image](https://user-images.githubusercontent.com/58305537/71101367-935d8200-2184-11ea-8dd3-42572df46881.png)

Expected behaviour:
Gives your primal strike, stormstrike, and lava lash a 15%, 30%, 45% chance to proc a lightening shield attack when casted.

**Comment by cryptid123** [comment]
This report is based off of examined numbers, not a possibly bugged tooltip.
