### ISSUE TITLE
Artisan Quiver

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#195]
Description:
Increase the damage of your auto-attacks by 15%.

Current behaviour:
Scaling is slightly higher than 15%.
![image](https://user-images.githubusercontent.com/58305537/71183880-be100f00-2246-11ea-90a7-41823ff41ef6.png)

Expected behaviour:
Increase the damage of your auto-attacks by 15%.

**Comment by cryptid123** [comment]
This report is based off of examined numbers, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
results

before 2626

after 3020

3020/2626 = ~1.15004

working as intended.
