### ISSUE TITLE
Unholy might

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#197]
Description:
Increase your strength by 25%.

Current behaviour:
Strength increase is over scaling, by an apparent 31% instead of 25%.
![image](https://user-images.githubusercontent.com/58305537/71297228-9c02b380-2350-11ea-9118-590eec272b6c.png)

Expected behaviour:
Increase your strength by 25%.

**Comment by cryptid123** [comment]
This is not just a tooltip bug.

**Comment by therealsmf** [comment]
stacks with plate spec. You dont get the 5% strength buff without any talents.

strength

3306 (no spec)

3471 (frost spec) (5% upgrade from plate spec - 5% str)

4339 (uh spec) (25% upgrade over frost spec - 31.25% upgrade over no spec)


working as intended.
