### ISSUE TITLE
[Quest][Dragonblight] Sarathstra, Scourge of the North

### ISSUE THREAD

**Issue by omegaroll** [ProjectNelth/BugTracker#20]
Description: You need to kill an elite dragon who's flying in the air. To kill it, you need to ask your questgiver to call the dragon down to the ground. That part doesnt work.

Current behaviour: Rokhan (the questgiver) doesn't give the option to call down Sarathstra (the dragon)

Expected behaviour: Rokhan should have a speechbubble which says: "Get that frostwyrm on the ground and I'll finish her." After that, the dragon should come out of the air so you can kill it.

Links: https://www.youtube.com/watch?v=W83yBE_jbxE

**Comment by iRadioactive** [comment]
Quest will autocomplete for now, and we will go back to fixing the quest.
