### ISSUE TITLE
Halls of Reflection Heroic.

### ISSUE THREAD

**Issue by Refurinn** [ProjectNelth/BugTracker#204]
Current behaviour: During the first boss encounter with Falric and Marwyn. While you're killing waves of adds the whole event just despawns after wave 4/10 rather than spawning wave 5 and the first boss. And the Waves of adds are just immobile rather than going aggressive and chasing you.

Expected behaviour: Event to not cancel during the waves. And waves of adds actually being mobile and move towards the party / player

Links:

**Comment by Refurinn** [comment]
Halls of Reflection Normal is finishable cause the whole event doesn't despawn. But npc's during the waves are still immobile.

**Comment by therealsmf** [comment]
should be already reported in the big dungeon notepads. if the issue still exists after changes, reopen on the forum :)
