### ISSUE TITLE
Stacked NPCs

### ISSUE THREAD

**Issue by hh2h** [ProjectNelth/BugTracker#209]
Description:
Bloodhoof Vilage
NPC - Tarl Cloudsong <Shaman Trainer>
NPC - Narm Skychaser <Shaman Trainer>

Current behaviour:
They are stacked.
Expected behaviour:
They must be spreaded.
Links:
https://imgur.com/a/RLBLq6w

**Comment by PN-Cryptid** [comment]
> Description:
> Bloodhoof Vilage
> NPC - Tarl Cloudsong
> NPC - Narm Skychaser
> 
> Current behaviour:
> They are stacked.
> Expected behaviour:
> They must be spreaded.
> Links:
> https://imgur.com/a/RLBLq6w

Bloodhoof village has been heavily reworked, scripted, and cleaned.
