### ISSUE TITLE
Pit of Sauron - completely bugged. 

### ISSUE THREAD

**Issue by Popel123** [ProjectNelth/BugTracker#213]
Description: Quest solved automatically. first 2 bosses are good. last boss doesn't appear. Mobs are half dead. Mobs cant attack me or I cant attack them.

Current behaviour:

Expected behaviour:

Links:

**Comment by therealsmf** [comment]
should be already reported in the big dungeon issues notepads. if the issue still exists after changes, reopen on the forum :)
