### ISSUE TITLE
[NPC] Shardhorn Rhino- Sholazar Basin

### ISSUE THREAD

**Issue by mkotil** [ProjectNelth/BugTracker#22]
Description: NPC is bugged

Current behaviour: The NPC remains frozen and is unable to be attacked, therefore, preventing the completion of quests involving the NPC.

Expected behaviour: NPC should be attackable

Links:

**Comment by iRadioactive** [comment]
Was not able to reproduce your issue, could you provide more info or screenshot/gif?
