### ISSUE TITLE
Quest : Captives at Deatholme - Ghostlands quest

### ISSUE THREAD

**Issue by MissCllick** [ProjectNelth/BugTracker#220]
Description:
After u rescue Enith and Varnis the mark place of third - Ranger Vedoran just disappears from map location.... have to find him on own hand which is difficult.... XD
Current behaviour:

Expected behaviour:

Links:

**Comment by therealsmf** [comment]
should be reported in the big zone reports on the questing spreadsheet. if the issue still exists after changes, reopen on the forum :)
