### ISSUE TITLE
 Quest. Exodus

### ISSUE THREAD

**Issue by lillemand13** [ProjectNelth/BugTracker#225]
Description: Bugs if you are in any form shape shift as a druid 

Current behaviour: you cant talk with it as it takes of as you right click it and leave you behind if you are shapeshifted 

Expected behaviour: you should be able to talk with it and tell that you are ready

Links: https://www.wowhead.com/quest=24438/exodus

**Comment by therealsmf** [comment]
i believe it should give you the error message saying you are shapeshifted if you pick the option. if the escort starts automatically then thats another issue.
