### ISSUE TITLE
NPC. Stromglen Village

### ISSUE THREAD

**Issue by lillemand13** [ProjectNelth/BugTracker#226]
Description: The profession trainer ( Jack "All-Trades Derrington )

Current behaviour: He wont let you click in under the sub menus in his "press more section" so you cant learn all professions 

Expected behaviour: you should be able to choose more the just 5 professions in the chat menu he got 

Links: https://www.wowhead.com/npc=50247/jack-all-trades-derrington

**Comment by therealsmf** [comment]
should be reported in the big zone reports on the questing spreadsheet. if the issue still exists after changes, reopen on the forum :)
