### ISSUE TITLE
Broken quest at Merchant square

### ISSUE THREAD

**Issue by lillemand13** [ProjectNelth/BugTracker#230]
Description: You cant get help from the npc in the quest " The Battle for Gilneas City " 

Current behaviour: You are not getting help from the npc as you cant talk to the prince as he will only zone in as you inter the city and will zone out when you leave 

Expected behaviour: Should spawn when you accept the quest so you can get help for clearing the city 

Links: https://www.wowhead.com/quest=24904/the-battle-for-gilneas-city

**Comment by therealsmf** [comment]
should be reported in the big zone reports on the questing spreadsheet. if the issue still exists after changes, reopen on the forum :)
