### ISSUE TITLE
Major Glitch 

### ISSUE THREAD

**Issue by lillemand13** [ProjectNelth/BugTracker#231]
Description:  "start" Hearthstone for Worgen to The Howling Oak 

Current behaviour: It will teleport you to Desolace in Kalimdor

Expected behaviour: Should teleport you to the Howling Oak

Links:

**Comment by Goztoc** [comment]
I can't seem to do this. Can you guide me step by step? I've tested multiple classes on a Worgen and the starting heartstone seems to be working fine. 

The Howling Oak is located in Darnassus.
