### ISSUE TITLE
[starting area] [ Deathknight] 

### ISSUE THREAD

**Issue by Icyytouch** [ProjectNelth/BugTracker#236]
Description:
its almost the end of the quest line where we fight the forces with frost wyrm.
Current behaviour:
after that quest lich king disappear along with that stairs of his on death breach, and I went to ebonhold then came back down and saw that he was present there
Expected behaviour:
shouldn't disappear 
Links:

**Comment by therealsmf** [comment]
Player is phased away after completing An End To All Things... (12779). Have to go up to Ebon Hold and down again to be able to continue the chain.
