### ISSUE TITLE
[Class] [Death Knight] [Glyph] Glyph of Resilient Grip

### ISSUE THREAD

**Issue by Heroclassx** [ProjectNelth/BugTracker#241]
Description: When your Death Grip ability fails becasue its target is immune, its cooldown is reset.

Current behaviour: It dosent reset

Expected behaviour: it should reset its cooldown

Links:
https://streamable.com/pnv6se

**Comment by WufcPN** [comment]
This issue has been fixed and is now applied to the realm.
