### ISSUE TITLE
[Death Knight] [Spell] Death and Decay

### ISSUE THREAD

**Issue by afdruiprekje** [ProjectNelth/BugTracker#242]
Description: Death and Decay, Corrupts the targeted ground, causing [(3.6036% of Attack power) * 11] Shadow damage over 10 sec to targets within the area.

Current behaviour: Bug which causes Death and Decay to do no damage if the Death Knight casts it with Anti-Magic Shell active.

Expected behaviour: Death and Decay should deal damage even when Anti-Magic Shell is active.

Links:
https://streamable.com/s59c8h

**Comment by WufcPN** [comment]
This issue has been dealt with and is now applied to Neltharion
