### ISSUE TITLE
[NPC] Guards don't stop walking

### ISSUE THREAD

**Issue by afdruiprekje** [ProjectNelth/BugTracker#244]
Description: Some guards have a path they follow, they walk around.

Current behaviour: When you click on the guard to ask directions, he keeps on walking.

Expected behaviour: The guard should stop walking when interacted with.

Links: https://streamable.com/w6no9z

**Comment by PN-Cryptid** [comment]
Good find.

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/npc-guards-dont-stop-walking-r76/
