### ISSUE TITLE
Deep Earth Battlegarb 4set effect (Feral druid T13 4set)

### ISSUE THREAD

**Issue by therealsmf** [ProjectNelth/BugTracker#246]
Description: There is no debuff or any visual indicator for the 15 second timer after shifting into cat/bear form.

Current behaviour: The set effects work perfectly. However, druids can not determine (without setting a stopwatch macro) when their 4set effects can be used and benefited from. This can make druids "waste" their Tiger's Fury/Frenzied Regeneration because they aren't shown the "ICD".

Expected behaviour: The druid should get a debuff called Recently Shapeshifted (spellID 108095) that lasts 15 seconds after shifting into cat/bear form, that doesn't let the 4set effect work while active. 

Links: https://www.wowhead.com/spell=105735/item-druid-t13-feral-4p-bonus-might-of-ursoc-and-stampede#comments

**Comment by WufcPN** [comment]
This issue has been fixed and is now applied on Neltharion
