### ISSUE TITLE
Flamestrike

### ISSUE THREAD

**Issue by therealsmf** [ProjectNelth/BugTracker#248]
Description: The afterburn effect of flamestrike does not get affected by the damage boosting multipliers of Fire Specialization (Fire mage passive buff) OR Flashburn (Fire mage mastery).

Current behaviour: Flamestrike "dot" deals the same damage regardless of spec/mastery rating. Only the initial damage is buffed correctly.

Expected behaviour: The damage should be multiplied by both of the specs passive buff as well as the mastery effect.

Links: https://i.imgur.com/Qae6thf.png

**Comment by PN-Cryptid** [comment]
please check this again

**Comment by therealsmf** [comment]
nope, still unaffected by both mastery and fire spec.
