### ISSUE TITLE
Frostfire bolt - Fire specialization

### ISSUE THREAD

**Issue by therealsmf** [ProjectNelth/BugTracker#249]
Description: The damage of FFB does not get affected by the damage boosting multiplier of Fire Specialization (Fire mage passive buff)

Current behaviour: FFB deals the same damage regardless of spec. (no talents vs 1 point in fire tree for the buffs.)

Expected behaviour: The damage should be multiplied by 1.25 whenever the mage has Fire Specialization.

Links: https://i.imgur.com/BLCn86n.png

**Comment by PN-Cryptid** [comment]
Works fine now.
![image](https://user-images.githubusercontent.com/58305537/119686577-75359000-be14-11eb-9c05-db7b9c16693c.png)
