### ISSUE TITLE
Mobs already dead

### ISSUE THREAD

**Issue by Sardean** [ProjectNelth/BugTracker#25]
Description:
Thousand Needles around "Fizzle and Pozzik's Speedbarge. No one else has been online and mobs are already killed. Ex. Whale Shark, Sparkleshell Snapper, Saltstone Crystalhide.
Current behaviour:
Mobs already dead and bodies remain.
Expected behaviour:
Mobs should already be alive or atleast respawn and be killable.
Links:

**Comment by iRadioactive** [comment]
I believe these mobs are supposed to be dead?
https://www.wowhead.com/npc=41099/saltstone-crystalhide#comments
https://www.wowhead.com/npc=41103/sparkleshell-snapper#comments
https://www.wowhead.com/npc=48185/whale-shark#comments
