### ISSUE TITLE
Bird of Prey: Disarm

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#253]
Description:
Bird of prey pets (specifically owl) should have a single disarm.

Current behaviour:
Bird of prey pets currently have access to two identical disarms. Both Disarms share a cooldown and diminishing return, so the scorpion disarm is just a nuisance spell present.

![image](https://user-images.githubusercontent.com/58305537/90980974-612ecc00-e52c-11ea-9e20-e09c926d6eb5.png)

Expected behaviour:
Bird of prey pets (owl) should not have access to the scorpion disarm.

Links:

**Comment by Hyjarion** [comment]
fixed
