### ISSUE TITLE
[DR](Dispel) Unstable Affliction

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#254]
Description:
![image](https://user-images.githubusercontent.com/58305537/90981074-ff229680-e52c-11ea-8643-40934aefc6b8.png)

Current behaviour:
The silence from unstable affliction is not on the silence DR.

Expected behaviour:
This debuff should be on the silence DR.

Links:
https://wow.gamepedia.com/Unstable_Affliction

**Comment by therealsmf** [comment]
The Burning Crusade Patch 2.3.0 (2007-11-13): The silence from this ability is now subject to diminishing returns.

**Comment by iRadioactive** [comment]
Fixed & Closed
