### ISSUE TITLE
[DR] Earth's Grasp

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#256]
Description:
![image](https://user-images.githubusercontent.com/58305537/90981406-c97ead00-e52e-11ea-9e5e-ad6b02325071.png)

Current behaviour:
Earth's grasp is not on any DR.

Expected behaviour:
Earth's grasp should be on the controlled root DR.

**Comment by therealsmf** [comment]
duplicated report 189
