### ISSUE TITLE
[DR] Intercept

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#257]
Description:
![image](https://user-images.githubusercontent.com/58305537/90981458-22e6dc00-e52f-11ea-8361-2593b4ca1839.png)

Current behaviour:
Warrior intercept is not on the controlled stun DR.

Expected behaviour:
Warrior intercept should be on the controlled stun DR.

**Comment by therealsmf** [comment]
Cataclysm Patch 4.1.0 (2011-04-26): [Charge] and  [Intercept] no longer have diminishing returns on their stun effects.
