### ISSUE TITLE
Speedbarge Diving Helm Buff

### ISSUE THREAD

**Issue by Sardean** [ProjectNelth/BugTracker#26]
Description:
Recieved the Speedbarge Diving Helm Buff as soon as I got in the water in Thousand Needles. you should not recieve the buff unless doiing the quest for it which I never did. The buff also remains constant even on land so my run spand out of the water is also increased in Thousand Needles.
Current behaviour:
Speedbarge Diving Helm Buff, instantly given and remains outside the water.
Expected behaviour:
Should only be available through quest and only work on the ocean floor in thousand needles. 
Links:

**Comment by therealsmf** [comment]
should be reported in the big zone reports on the questing spreadsheet. if the issue still exists after changes, reopen on the forum :)
