### ISSUE TITLE
[DR] Throwdown

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#260]
Description:
![image](https://user-images.githubusercontent.com/58305537/90981897-98ec4280-e531-11ea-92f2-d874bf8c4422.png)

Current behaviour:
Targets immune to throwdown via DR are still rooted and put through the animation of being thrown down.

Expected behaviour:
Targets immune to throwdown via DR should not be rooted or put through the animation of throwdown.

**Comment by therealsmf** [comment]
knockdown and stun are 2 separate mechanics. throwdown does both. the knockdown does not DR. https://wow.gamepedia.com/Throwdown
