### ISSUE TITLE
Flight Form Replacement

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#266]
Description:
Swift flight form should replace normal flight form.

Current behaviour:
Both flight form and swift flight form can coexist.
![image](https://user-images.githubusercontent.com/58305537/90985659-651e1680-e54b-11ea-89b9-a1cc3a85c61d.png)

Expected behaviour:
druid swift flight form should completely replace normal flight form. 

Links:
https://youtu.be/tOGhgO_0gCk?t=14

**Comment by iRadioactive** [comment]
Fixed.
