### ISSUE TITLE
Bind Elemental

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#267]
Description:
![image](https://user-images.githubusercontent.com/58305537/90985726-bfb77280-e54b-11ea-8cca-7f4d4dcfe483.png)

Current behaviour:
Earth elemental is immune to bind elemental

Expected behaviour:
Earth elemental should not be immune to bind elemental.

**Comment by WufcPN** [comment]
This issue has been fixed 

Credits: Hyjarion
