### ISSUE TITLE
Megs Dreadshredder Unacceptable Quest

### ISSUE THREAD

**Issue by Sardean** [ProjectNelth/BugTracker#27]
Description:
After turning in the Warchief's quest to go to Tanaris. you are unable to accept any quest from Megs Dreadshredder in Gadgetzan, which is the first quest you're supposed to begin with.
Current behaviour:
Cannot recieve quest from NPC.
Expected behaviour:
Should have 4 quest total that am able to recieve.
Links:

**Comment by iRadioactive** [comment]
Should be able to move on now. We need to go over several quests in tanaris.
