### ISSUE TITLE
Targeting

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#273]
Description:
An issue that causes abilities and commands to target the wrong player.

Current behaviour:
-Addons which inspect players on mouseover to pull their stats will leave that person as their target server-side.
Example: TipTac (TipTacItemRef sub-addon)
[Download TipTac.zip](https://github.com/ProjectNelth/BugTracker/files/5374335/TipTac.zip)

-Charging a focus or mouseover target (without manually setting that focus or mouseover as your target) will leave that focus/mouseover as your server-side autoattack target. At this point your client and the server will display different units as your target.

Expected behaviour:
The server should not leave a focus or mouseover target as your main target after performing functions that require targeting.

One lead I had from looking at the addon:
[https://wowwiki.fandom.com/wiki/API_NotifyInspect](url)

**Comment by PN-Cryptid** [comment]
[https://wowwiki.fandom.com/wiki/API_NotifyInspect](url)

**Comment by therealsmf** [comment]
Initial symptoms were noticed over 10 months ago. (mouseover misdirection, then multishot says "invalid target" -> server thinks the person you are MDing is your target.) Took a while to figure it out. 
![image](https://user-images.githubusercontent.com/66882878/95947820-b7631180-0def-11eb-8216-e9e52a2dcc44.png) 

Here's a gif of it in action. (as soon as the mage flies by, i do mouseover MD, keep spamming multishot, error message says "invalid target". https://giant.gfycat.com/PitifulFakeAgama.mp4

**Comment by PN-Cryptid** [comment]
Fixed for all scenarios except casting charge on non-victim("target" frame) targets.

**Comment by therealsmf** [comment]
![image](https://user-images.githubusercontent.com/66882878/120930655-8b81fc80-c6ee-11eb-962d-20cb3bb489ea.png)

**Comment by therealsmf** [comment]
https://github.com/ProjectNelth/BugTracker/issues/351
