### ISSUE TITLE
[List] Warsong Gulch

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#275]
**Achievements HAVE been checked for this BG**

- [Ach] Ironman: Ach is earned even if you have deaths.

- ~~Flag return event does not check for a flag carrier being on the capture point for an immediate capture.~~

- ~~Alliance flag icon replaced by a crystal formation.~~

- ~~Anticheat *should* undo recent scores by cheaters.~~ (for future development)

**Comment by Saintagony** [comment]
Capture the Flag Debuffs: Focused/Brutal Assault debuffs inaccurate timers. Should begin a 3 min. countdown once both flags have been picked up till first debuff from Focused Assault begins. After 3 min the 4th debuff should change to Brutal Assault debuff.
Debuff should also stack to 10 totaling at 100%, it currently stops at 9 stacks with 90% reduction.
How it currently is - Starts countdown after 60 seconds, and stays in 60 second increment's. Currently switches debuff on the 7th stack when it should be on the 4th stack at the 7 min. mark.
If both flag carriers have carrier debuff, and one holding the flag leaves or dies, you should still have the debuff, it works and still applies to the other FC currently when the EFC is killed but if EFC leaves then the debuff dissapears on the other FC, and if new EFC picks up the flag after they leave then that carrier gets the debuff but the other FC loses the debuff.
https://www.youtube.com/watch?v=kWZCfogumJE +8:26 you see EFC died but he still has debuff
References:
https://www.wowhead.com/news=183948/ptr-patch-4-1-notes-updated-2-28#news-post-183948
https://www.youtube.com/watch?v=-ob4thrgr9w 2:40 Both flags picked up
5:39 1st Debuff
6:42 2nd Debuff
7:42 3rd Debuff
8:40 4th Debuff changes to Brutal Assault

**Comment by PN-Cryptid** [comment]
> **How it should work: Capture the Flag Debuffs** Focused/Brutal Assault debuffs inaccurate timers. Should begin a 3 min. countdown once both flags have been picked up till first debuff from Focused Assault begins at the 3 min. mark, then 1 minute increment's should occur adding a stack at each min. and the 4th stack on the debuff should be at the 7 min. mark and then change to the Brutal Assault debuff.
> **How it currently works** - 1st debuff appears after 60 seconds, and stays stacking in 60 second increment's. While switching to debuff: Brutal Assault on the 7th stack.
> **How it should work Debuff:** Should also stack to 10 totaling at 100% reduction.
> **How it currently works** - Stops at 9 stacks with 90% reduction.
> **How it should work:**
> 2.If the Flag is dropped with stack(s) but not returned, the next player to pick up the Flag should have the same stacks(1-10).
> Ex. Ally FC had 6 stacks then drops the flag and a new Alliance player picks up the flag, he now has 6 stacks.
> 3.If the Flag is dropped with stack(s) and is returned, the next player to pick up the Flag should have 0 stacks.
> Ex. Ally FC had 6 stacks then drops the flag and it's returned. A new Ally FC picks up the flag with 0 stacks.
> **How it currently works:**
> 2.Flag carrier that has stacks but isn't returned, the next players' stack is reset back to 1 no matter what the stack amount was.
> 3.Flag carrier that has stacks that was returned when picked up again won't have stacks which is[correct] but
> if you drop the flag again right after you've picked it back up, the stacks reset back to 1.
> 
> **References:** These are videos from twin peaks, but they're referring to the flags+flag carrying debuffs itself so I'm pretty certain it applies the same way to both WSG and Twin Peaks.
> https://www.wowhead.com/news=183948/ptr-patch-4-1-notes-updated-2-28#news-post-183948
> https://www.youtube.com/watch?v=kWZCfogumJE
> +8:26 You see EFC died but he still has debuff
> https://www.youtube.com/watch?v=-ob4thrgr9w 2:40 Both flags picked up
> 5:39 1st Debuff
> 6:42 2nd Debuff
> 7:42 3rd Debuff
> 8:40 4th Debuff changes to Brutal Assault

Fixed.

**Comment by therealsmf** [comment]
achievements are globally given despite requirements not being met - from what i know its just a toggle in the worldserver or core config. everything else is correct so gonna close this.
