### ISSUE TITLE
[List] Strand of the Ancients

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#276]
**Achievements have not been checked for this BG**

- ~~Turrets can be shadowstepped~~
(hotfixed post cata)

- ~~Gates can be destroyed out of sequence, but the orb cannot be used until a path has been cleared.~~ fixed

- ~~Graveyard flags should not be interactable by the defending team after they have been taken by the attackers.~~ fixed

- ~~Turrets should deal 20k base damage and be affected by resil, currently only deals 2k. (10x multiplier missing)~~

- ~~There should be a mass stun and few second delay before the "switch sides" teleport occurs.~~

- ~~Missing explosives in final area, west side ([10:59:51]X: 979.852112 Y: -2.998101 Z: 86.710007 Orientation: 1.486402) (existing in code, not spawning atm)~~ fixed
![image](https://user-images.githubusercontent.com/58305537/96372888-1a79de80-1137-11eb-8533-59f5f9f5b6fc.png)

**Comment by thebotz** [comment]
As of 21/12/2020 :

- Anticheat can cause you to be teleported back into the water when jumping on the moving boat at the start.
- Vehicle damage ignores resilience.
- Demolishers 'Ram' ability is unable to hit players (but works on doors)
- After switching sides, the boats start already at their destination.
- Vehicles are lvl 85 even in low-lvl versions of the battleground (but their damage does scale down).

**Comment by Saintagony** [comment]
Teleporters currently teleport you to the same colored gate jut behind the wall. Should be  if a player clicks the Teleporter at the Blue gate when one of the beach gates has been destroyed, it will put the player behind the Red gate.
https://worldofwarcraft.com/en-us/news/2166872/patch-406-official-notes

**Comment by PN-Cryptid** [comment]
> Teleporters currently teleport you to the same colored gate just behind the wall. Should be if a player clicks the Teleporter at the Blue gate when one of the beach gates has been destroyed, it will put the player behind the Red gate.
> https://worldofwarcraft.com/en-us/news/2166872/patch-406-official-notes

Fixed.

**Comment by PN-Cryptid** [comment]
> As of 21/12/2020 :
> 
> * Anticheat can cause you to be teleported back into the water when jumping on the moving boat at the start.
> * Vehicle damage ignores resilience.
> * Demolishers 'Ram' ability is unable to hit players (but works on doors). It should deal damage to and knockback players.
> * After switching sides, the boats start already at their destination.
> * Vehicles are lvl 85 even in low-lvl versions of the battleground (but their damage does scale down).
> * Vehicles are capable of dodging/parrying attacks.
> * Demolishers can be affected by hungering cold. They should only be affected by slows and roots but not by any sort of loss of control.
> 
> https://www.youtube.com/watch?v=lqvyqYZ8aPc - Reference video from patch 4.2, no relevant changes have been done to the battleground between that patch and 4.3.4.

Updated demolisher immunity to permit snares but ignore hard crowd controls and roots.

**Comment by PN-Cryptid** [comment]
> > As of 21/12/2020 :
> > 
> > * Anticheat can cause you to be teleported back into the water when jumping on the moving boat at the start.
> > * Vehicle damage ignores resilience.
> > * Demolishers 'Ram' ability is unable to hit players (but works on doors). It should deal damage to and knockback players.
> > * After switching sides, the boats start already at their destination.
> > * Vehicles are lvl 85 even in low-lvl versions of the battleground (but their damage does scale down).
> > * Vehicles are capable of dodging/parrying attacks.
> > * Demolishers can be affected by hungering cold. They should only be affected by slows and roots but not by any sort of loss of control.
> > 
> > https://www.youtube.com/watch?v=lqvyqYZ8aPc - Reference video from patch 4.2, no relevant changes have been done to the battleground between that patch and 4.3.4.
> 
> Updated demolisher immunity to permit snares but ignore hard crowd controls and roots.
> During testing, this revealed that demolishers return "invalid target" when you attempt to dispel them.

Demolisher immunities all corrected

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/bg-strand-of-the-ancients-r88/
