### ISSUE TITLE
[List] Twin Peaks

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#277]
### **Achievements**

- I'm in the black lodge is earned with a single kill.
- I'm in the white lodge is earned with a single kill.
- Soaring spirits gets double credits.
- Wild Hammering gets double credits per kill.
- Double jeopardy earned without being two points behind at all.

### Other

- ~~Alliance east gate is too far "outside", allowing players to mount up inside the gate.~~(fixed)

- ~~Lots of static excess floating npcs above the waterfall.~~(fixed)

- ~~Brutal Assault timing wrong.~~(fixed)

- ~~Over the waterfall, there should be a killzone starting where your camera currently stops dropping.~~ (fixed)

- ~~Flag return event does not check for a flag carrier being on the capture point for an immediate capture.~~(fixed)

- ~~Horde berserker buff should be outside the pig hut.~~(fixed)

- ~~Alliance flag icon is replaced by a crystal pixel formation.~~(fixed)

- ~~Bystander NPC movements that need correction:~~(fixed)

- Gryphon flight from nest to platform

- ~~Orcs cutting wood (ashenvale anim?)~~(fixed)

- ~~Berserker hut pigs should move to and from the trough.~~(fixed)

[Video Reference by jonjon](https://www.youtube.com/watch?v=PzHwn0BPbuw)

**Comment by PN-Cryptid** [comment]
Reference:
https://youtu.be/Cjj0Qo6AY9A

**Comment by Saintagony** [comment]
+Horde Berserker Buff in wrong location.
References:
https://www.youtube.com/watch?v=lHiMWLrGdz0 41 Seconds in
https://www.youtube.com/watch?v=62hQUJih6Qw 17:55 in

+Warlock's can use Demonic Circle to teleport with flag up to elevated GY when an aura should cause the flag to be reset. Priest cannot Leap of Faith someone up to the GY when they should be able to, and if they pull FC up then the flag should be reset.
Reference:
https://worldofwarcraft.com/en-us/news/2259389/patch-406-hotfixes-march-29

**Comment by Saintagony** [comment]
Capture the Flag Debuffs: Focused/Brutal Assault debuffs inaccurate timers. Should begin a 3 min. countdown once both flags have been picked up till first debuff from Focused Assault begins. After 3 min the 4th debuff should change to Brutal Assault debuff.

How it currently is - Starts after 60 seconds, and stays in 60 second increment's. Currently switches debuff on the 7th stack.

References:
https://www.youtube.com/watch?v=-ob4thrgr9w 2:40 Both flags picked up
5:39 1st Debuff
6:42 2nd Debuff
7:42 3rd Debuff
8:40 4th Debuff changes to Brutal Assault

**Comment by therealsmf** [comment]
focused and brutal assault fixed as of https://forum.projectnelth.com/topic/69-changelog-march-6-2021/
achievement list moved to https://forum.projectnelth.com/bugtracker/twin-peaks-achievements-r89/
