### ISSUE TITLE
[List] Alterac Valley

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#278]
**Achievements have not been checked for this BG**

- ~~Alliance gates are too far "outside", allowing players to mount up inside the gate. the gate should be moved back to the mount/nomount line.~~(fixed)

~~https://www.youtube.com/watch?v=CnI_rNE3me4~~(fixed)

- ~~Boss auras issue - boss should lose the tower aura when each towers' npc is killed, currently the buff only fades when the bases are taken.~~(fixed)

- ~~Alliance tower guards have a fel reaver polearm as a weapon~~ (fixed)

- "Not enough players" time is over 24h, should be 5 minutes.

- ~~Each starting cave has two packs that should be patrolling back and forth between the endpoints and midpoint of their respective caves. Alliance has a battleguard followed by two owls, and the horde has a battleguard followed by two bloodhounds for each pack.~~ (fixed)

- ~~Icewing marshal buff has 100 yard radius and effects players. This is the only marshal/warmaster buff with an issue.~~ (fixed)

- "Lokholar the Ice lord" and "Ivus the forest lord" quests should not be flagged as repeatable, but rather reset on the AddPlayer Event within the AV script.

- "Gallons of blood" and "Crystal Cluster" should not be available until "lokholar the ice lord" and "Ivus the forest lord" have been completed.

- ~~Archers currently are doing half damage but at double the attack rate to allow them their intended DPS at the required range with existing spells.~~ (fixed)

- Ivus and Lokholar are currently summoned immediately upon completing the required amount of quests, there should be a scripted phase where the druids/shamans ride towards the middle and tell 10 players to channel click a stone.

- ~~Warmasters and Marshals currently do not respawn on general reset.~~(fixed)

- ~~Crossfaction players see both enemy and friendly graveyard guards as neutral, and will be ignored by them if not engaged.~~(fixed)

- ~~Graveyard capture time seems to be higher than 4 minutes.~~(fixed)

**Comment by Saintagony** [comment]
Health for Balinda is currently[5412k]
Health for Galvangar is currently [5412k]
Balinda Stonehearth Health should be [3,874,500]
https://wowwiki.fandom.com/wiki/Balinda_Stonehearth#Patch_changes
https://www.youtube.com/watch?v=Uga3A5-haQk [3:01 Health preview]
Captain Galvangar Health should be [3,874,500]
https://wowwiki.fandom.com/wiki/Captain_Galvangar
https://www.youtube.com/watch?v=H_wlbWPdY6k [2:55 Health preview]

**Comment by Saintagony** [comment]
Health Preview:
Currently some NPC's gain Marshal Health Buff near boss when they shouldn't. (Murgot Deepforge, Dirk Swindle, Athramanis, Lana Thunderbrew, Seasoned Defender's near boss room)
https://www.youtube.com/watch?v=fx-MbzyrO_k&t=60s 1:52 Show all tower points are still up and there's no Marshal Buff displayed onto Murgot Deepforge.
https://www.youtube.com/watch?v=fx-MbzyrO_k&t=60s 0:55 for LVL84/1:57 for LVL 85 | Stormpike Bowman - Health 96744 LvL 84 / Stormpike Bowman - Health 116,235 LvL 85 - Currently isn't appearing

https://www.youtube.com/watch?v=SBFzUkWY2mM 2:32 Bowman defending Bunker LvL 84 | 3:27 Stormpike Defender LvL 83
https://www.youtube.com/watch?v=tMuItilm468&t=75s 1:20 Tower's and Bunker's should be defended by Bowman not Defender's.
https://www.youtube.com/watch?v=tMuItilm468&t=75s 3:39 You'll see the dead Guardians.
https://www.youtube.com/watch?v=SBFzUkWY2mM 3:56 Stormpike Defender's health 21,472

Graveyard:
Frostwolf Graveyard - Guardians are not centered around the flag.

NPC's:
Stormpike Bowman LvL 84/85 Health 96,744/116,235 | Should be guarding faction controlled Bunkers
Frostwolf Bowman LvL 84/85 Health 96,744/116,235 | Should be guarding faction controlled Towers

Frostwolf Guardian/Stormpike Defender - Should only appear at faction controlled graveyards(Currently guard towers as well) - Incorrect Heallth amounts. 
1}Quest in which they upgrade from, Horde quest ID[7224]Enemy Boot and Alliance quest ID[7223]Armor Scraps.Should upgrade with a total of 1500 Armor Scraps, 500 per troop upgrade.
Each troop upgrade should give a periodic buff to your melee and spell damage. that scales from 10% at the Seasoned unit level, 20% at the Veteran unit level, and 30% at the Champion unit level.
1}https://wowwiki-archive.fandom.com/wiki/Alterac_Valley#Battle_Quests
2}https://wowwiki-archive.fandom.com/wiki/Frostwolf_Guardian
2}Frostwolf Guardian (21,472 LVL 83) >>> Seasoned Guardian (32,248 LVL 84) >>> Veteran Guardian (46,494 LVL 85) >>> Champion Guardian (Unknown yet)
3}https://wowwiki-archive.fandom.com/wiki/Stormpike_Defender
3}Stormpike Defender (21,472 LVL 83) >>> Seasoned Defender (32,248 LVL 84) >>> Veteran Defender (46,494 LVL 85) >>> Champion Defender (Unknown yet)

Currently begins with Seasoned guardian (Health 83845 LVL 84) then with 500 Scraps >>> turns into Veteran Guardian (LVL ranging from 75-85) gives you a 30 min periodic armor buff for 10% which should be Melee and Spell Damage buff.

**Comment by PN-Cryptid** [comment]
Icewing marshal buff has too large of radius, is buffing outside NPCs.

**Comment by PN-Cryptid** [comment]
Fixed all known issues so far, excluding icewing marshal buff radius and "Not enough players" timeout time.

**Comment by PN-Cryptid** [comment]
> Health for Balinda is currently[5412k] - Mana is currently [308k]
> Health for Galvangar is currently [5412k]
> Balinda Stonehearth Health should be [3,874,500] - Mana should be [267,240]
> https://wowwiki.fandom.com/wiki/Balinda_Stonehearth#Patch_changes
> https://www.youtube.com/watch?v=Uga3A5-haQk [3:01 Health preview][3:38 Mana preview]
> Captain Galvangar Health should be [3,874,500]
> https://wowwiki.fandom.com/wiki/Captain_Galvangar
> https://www.youtube.com/watch?v=H_wlbWPdY6k [2:55 Health preview]
> 
> Drek'Thar/Vanndar Stormpike should have the same health
> https://wowwiki.fandom.com/wiki/Drek%27Thar and https://wowwiki.fandom.com/wiki/Vanndar_Stormpike
> Health for Vanndar and Drek’Thar Currently
> 1.[5601k Health Currently with 0 towers
> 2.[7282k] Health Currently with 1 tower
> 3.[9466k] Health Currently with 2 towers
> 4.[12306k] Health Currently with 3 towers
> 5.[15998k] Health Currently with 4 towers
> 
> Health for Vanndar and Drek’Thar Should Be
> 1.[5,613,650] should be, with 0 towers
> https://www.youtube.com/watch?v=tMuItilm468 4:08 Health preview with no tower buffs.
> 2.[7300k] | should be with 1 tower
> https://www.youtube.com/watch?v=Uga3A5-haQk 11:50 Health preview with 1 tower buff.
> 3.[9487k] |should be with 2 towers
> https://www.youtube.com/watch?v=Bw72XYGITi4 6:24 Health preview with 2 tower buffs.
> 4._No proof yet so it’s estimated_
> 5.[16033k] | should be with 4 towers
> https://www.youtube.com/watch?v=ltIMFjhQRM0&t=412s 6:53 Health preview with all 4 tower buffs.

fixed.

**Comment by PN-Cryptid** [comment]
> Health Preview:
> Currently some NPC's gain Marshal Health Buff near boss when they shouldn't. (Murgot Deepforge, Dirk Swindle, Athramanis, Lana Thunderbrew, Seasoned Defender's near boss room)
> https://www.youtube.com/watch?v=fx-MbzyrO_k&t=60s 1:52 Show all tower points are still up and there's no Marshal Buff displayed onto Murgot Deepforge.
> https://www.youtube.com/watch?v=fx-MbzyrO_k&t=60s 0:55 for LVL84/1:57 for LVL 85 | Stormpike Bowman - Health 96744 LvL 84 / Stormpike Bowman - Health 116,235 LvL 85 - Currently isn't appearing
> 
> https://www.youtube.com/watch?v=SBFzUkWY2mM 2:32 Bowman defending Bunker LvL 84 | 3:27 Stormpike Defender LvL 83
> https://www.youtube.com/watch?v=tMuItilm468&t=75s 1:20 Tower's and Bunker's should be defended by Bowman not Defender's.
> https://www.youtube.com/watch?v=tMuItilm468&t=75s 3:39 You'll see the dead Guardians.
> https://www.youtube.com/watch?v=SBFzUkWY2mM 3:56 Stormpike Defender's health 21,472
> 
> Graveyard:
> Frostwolf Graveyard - Guardians are not centered around the flag.
> 
> NPC's:
> Stormpike Bowman LvL 84/85 Health 96,744/116,235 | Should be guarding faction controlled Bunkers
> Frostwolf Bowman LvL 84/85 Health 96,744/116,235 | Should be guarding faction controlled Towers
> 
> Frostwolf Guardian/Stormpike Defender - Should only appear at faction controlled graveyards(Currently guard towers as well) - Incorrect Heallth amounts.
> 1}Quest in which they upgrade from, Horde quest ID[7224]Enemy Boot and Alliance quest ID[7223]Armor Scraps.Should upgrade with a total of 1500 Armor Scraps, 500 per troop upgrade.
> Each troop upgrade should give a periodic buff to your melee and spell damage. that scales from 10% at the Seasoned unit level, 20% at the Veteran unit level, and 30% at the Champion unit level.
> 1}https://wowwiki-archive.fandom.com/wiki/Alterac_Valley#Battle_Quests
> 2}https://wowwiki-archive.fandom.com/wiki/Frostwolf_Guardian
> 2}Frostwolf Guardian (21,472 LVL 83) >>> Seasoned Guardian (32,248 LVL 84) >>> Veteran Guardian (46,494 LVL 85) >>> Champion Guardian (Unknown yet)
> 3}https://wowwiki-archive.fandom.com/wiki/Stormpike_Defender
> 3}Stormpike Defender (21,472 LVL 83) >>> Seasoned Defender (32,248 LVL 84) >>> Veteran Defender (46,494 LVL 85) >>> Champion Defender (Unknown yet)
> 
> Currently begins with Seasoned guardian (Health 83845 LVL 84) then with 500 Scraps >>> turns into Veteran Guardian (LVL ranging from 75-85) gives you a 30 min periodic armor buff for 10% which should be Melee and Spell Damage buff.
> 
> https://www.youtube.com/watch?v=SBFzUkWY2mM 10 Seconds in you can see the initial spawn graveyard should have I believe 8 Frostwolf Guardian's inside. Currently horde has none and alliance just has 3-4 LvL 61 Elites in there that shouldn't be.
> https://www.youtube.com/watch?v=tMuItilm468&t=75s 2 Seconds in you can see the same for alliance.
> 
> Stormpike Guardsmen/Frostwolf Legionnaire - Should be patrolling but are in one set place currently.
> 
> Wing Commander Guse - Not yet tested
> Wing Commander Slidore - Not yet tested

Fixed.

**Comment by Saintagony** [comment]
Reduce Warmaster Buff Radius on Vanndar | "It's extending to other Players and NPC's that shouldn't recieve it."
General's not resetting properly
<Missing> Sergeant Yazra Bloodsnarl - LVL 82 - Health 89,358 | https://youtu.be/H_wlbWPdY6k?t=308
Add Campfire "Horde" I have photos
Drek'Thar Health is off - Should be same as Vanndar but currently has less health @15,998k
Bowman should melee when in close range.
Bowman shouldn't despawn after flag cap, they last until killed. | https://youtu.be/UPuHLoAMPsE?t=215
Frostwolf Health - 10848 | https://youtu.be/PowJl2aqOqs?t=47
Add Frostwolfs I have locations of where they should be
No periodic buff that your teams General enables a melee and spell damage periodic buff (probably 30 minutes).. 10% increase at 500 armor scraps 20% at 1000 armor scraps and 30% at 1500 armor scraps
Frostwolf Wolf Rider Commander Missing - LVL 85 Elite - 619,920 | https://youtu.be/0nTqzodql9s?t=2 with Legionaires next to them
Frostwolf Stable Master Missing - LVL 85 Elite - 1,162,350 | https://youtu.be/0nTqzodql9s?t=2 with Legionaires next to them

https://www.youtube.com/watch?v=4DYBkR5sVd8 Pretty much all missing
More fireplace locations | https://www.youtube.com/watch?v=0Ul012zqxB8
Frostwolf should drop Frostwolf Hide

one camp fire im referrring too
![WoWScrnShot_032121_054902](https://user-images.githubusercontent.com/67765647/112204448-e8cadf00-8bd0-11eb-8669-6b87a4ccdb96.jpg)

both mines had something like this
![Uploading WoWScrnShot_032121_064442.jpg…]()

and when capping it through factions as well
the video links in there have locations for NPC's and if confused where frostwolf go just let me know,
horde side is missing like 6 maybe more Frostwolf

**Comment by PN-Cryptid** [comment]
Warmasters and Marshals will reset from a dead state if the boss leaves combat.

**Comment by PN-Cryptid** [comment]
Icewing marshal buff corrected.

**Comment by Saintagony** [comment]
Achievement(s):

- The Sticky Gazelle - Good
- Alterac Valley All-Star - Good
- Alterac Valley Victory - Good
- Frostwolf Perfection - Good
- Everything Counts - Good
- The Alterac Blitz - Good
- Loyal Defender - Good
- Tower Defense - Good
*Needs to despawn and then respawn on base defending for Tower/Bunker/GY points. Currently respawns more everytime when defending.
- Alterac Grave Robber - Good
- Hero of the Frostwolf Clan - Good
- Frostwolf Howler - Good
*Grunnda Wolfheart NPC - All items sold are supposed to require a certain reputation with Frostwolf Clan, currently only money/honor requirement is needed.
https://wowpedia.fandom.com/wiki/Grunnda_Wolfheart
- Alterac Valley Veteran - Good
- To the Looter Go the Spoils - Unable to complete/Bugged
*Needs drop rate chance increase from 0% to 1%.

**Comment by PN-Cryptid** [comment]
Looting [This item](https://www.wowhead.com/item=18228/autographed-picture-of-foror-tigule) does not grant an achievement.
loot chance set to 1% per mob listed: (13447, 22735, 31960, 37278, 12051, 22665, 31983, 37302, 12127, 22666, 32094, 37415, 12053, 22674, 37300, 12050, 22690, 32091, 37412)

**Comment by PN-Cryptid** [comment]
> >  - ~~Each starting cave has two packs that should be patrolling back and forth between the endpoints and midpoint of 
> > their respective caves. Alliance has a battleguard followed by two owls, and the horde has a battleguard followed by two 
> > bloodhounds for each pack.~~ (fixed)
 fixed

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/list-alterac-valley-r90/
