### ISSUE TITLE
[List] Battle for Gilneas

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#280]
**Achievements HAVE been checked for this BG**

- [Ach]Don't get cocky kid: earned by winning, even without ever being 500 points behind.

- [Ach]Jugger-not: earned by winning gilneas, even by a margin of more than 100 points.

- [Ach]Bustin' caps to make it haps: counter is added when the base is assaulted, not when it is taken.

**Comment by Saintagony** [comment]
Graveyard spawn locations inaccurate. With patch 4.1 the functionality of graveyards within the Battle for Gilneas was changed. Player's should not spawn at the base they die at even if it's under their teams control, but instead at the next nearest base.

+It's explained in the "Graveyard Use" section of Wiki webpage.
Link: https://wowwiki.fandom.com/wiki/Battle_for_Gilneas

**Comment by PN-Cryptid** [comment]
> Graveyard spawn locations inaccurate. With patch 4.1 the functionality of graveyards within the Battle for Gilneas was changed. Player's should not spawn at the base they die at even if it's under their teams control, but instead at the next nearest base.
> 
> +It's explained in the "Graveyard Use" section of Wiki webpage.
> https://www.wowhead.com/news=183948/ptr-patch-4-1-notes-updated-2-28#news-post-183948
> Link: https://wowwiki.fandom.com/wiki/Battle_for_Gilneas

Fixed in pull request #9 on my private repository.

**Comment by PN-Cryptid** [comment]
Capturing bases should spawn NPCs to work, similar to arathi basin.
[Video](https://youtu.be/nYTKULq-4Zg?t=169)

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/bg-battle-for-gilneas-r86/
