### ISSUE TITLE
[List] Ring of Valor

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#281]
- Pillars are always up, they should cycle up and down.

Reference:
https://youtu.be/QjdL_H3VADY

**Comment by Saintagony** [comment]
- Alliance joins facing away from gate. Horde facing Soulwell instead of opening door.

**Comment by PN-Cryptid** [comment]
> * Alliance joins facing away from gate. Horde facing Soulwell instead of opening door.

direction faced fixed.

Arena functionality fixed on dev realm. Since the dev core, functions regarding pillars have been updated and the arena pillars now "snap" into place.
