### ISSUE TITLE
[List] Isle of Conquest

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#282]
- ~~Isle of Conquest's issues center around the fact that lots of object and transport movements are out of sync.~~
### **Achievements**
**Achievements have not been checked for this BG**
### **Misc.**
- Friendly gates can be highlighted with a mouseover, they should not.
- Players are dismounted when using portals, but [should not be dismounted.](https://youtu.be/bj2iY29PeB0?t=325)
- ~~Friendly base flags can be interacted with, should be impossible.~~
- ~~(Docks, Workshop, Hanger) After the initial assault, map icons are not updated from one faction to contested. After a takeover, map icons are not updated from contested to the other faction.~~ fixed
- ~~Gunship icons are not displayed on map (reference: there's a horde gunship icon typically shown outside orgrimmar on the minimap. this is likely it's own npc/object that anchors the minimap icon.) [[video of gunship on map]]~~(https://youtu.be/DmtAzG9S2Z8?t=504)
- ~~Vehicle despawn/respawn issue experienced by cryptid and novaveteran: Vehicles are respawning in their death location rather than respawn point if dying out of their spawn base. When dying inside the spawn base, the vehicles do not respawn.~~
### **Quarry**
- no issues found
### **Refinery**
- no issues found
### **Workshop**
- ~~When the base changes control, the siege engine and one demolisher are left behind by the outgoing control faction.~~
### **Docks:**
- ~~When the base changes control, one glaive thrower and one catapult are left behind by the outgoing control faction.~~
- ~~Graveyard spawns you facing the docks, but [should spawn you facing the flag.](https://youtu.be/DmtAzG9S2Z8?t=633)~~
(Currently graveyard teleports do not adjust player orientation. Lacking data on all the orientations of every BG, this will remain untouched for now.)
- There should be a dock worker pacing around the docks,  his RP activity is unknown atm.
### **Hangar:**
- ~~Players on the ship before it starts moving will not receive a client update for the ship movement.~~ _This should never happen to non-GM players._
- ~~Portals on ships are not spawned.~~ not a bug afaik, parachutes are given on teleport up.
- ~~Portals take you nowhere.~~ fixed.
- ~~Southern gate portals do not de-spawn when the base is taken by the other team.~~
- ~~When the base is assaulted, opposing faction players are not teleported away from the active ship and down to the graveyard portal.~~
- ~~Portals lack glow effects:~~
![image](https://user-images.githubusercontent.com/58305537/106624417-a1ff2800-6543-11eb-8480-0a98f3b31f2a.png)
### **Alliance Keep**
- ~~one turret is hostile to alliance~~
- ~~Boss and mobs nearby have the wrong faction flag, they cannot be attacked by horde.~~
- ~~[Boss health should be 11628k.](https://youtu.be/IcabJ7nvgqg?t=404)~~
- ~~Boss and mobs nearby [should always be in a combat-ready stance.](https://youtu.be/DmtAzG9S2Z8?t=616)~~
- Boss resets at 30-40 yard radius, [should be unlimited.](https://www.wowhead.com/npc=34924/high-commander-halford-wyrmbane#comments:id=1658072)
- ~~Bombs are available to the wrong faction.~~
- One worker should pace between inside teleporters and do a "repair" on each.
- ~~Language.h values produce "x has captured the the (faction) keep."~~(fixed)
### **Horde Keep**
- ~~Boss and mobs nearby have the wrong faction flag. they cannot be attacked by alliance and are not aggressive to alliance.~~
- ~~[Boss health should be 11628k.](https://youtu.be/IcabJ7nvgqg?t=404)~~
- ~~Boss and mobs nearby [should always be in a combat-ready stance](https://youtu.be/DmtAzG9S2Z8?t=616).~~
- Boss resets at 30-40 yard radius, [should be unlimited.](https://www.wowhead.com/npc=34924/high-commander-halford-wyrmbane#comments:id=1658072)
- ~~Bombs are available to the wrong faction.~~
- One worker should pace between inside teleporters and do a "repair" on each.
- ~~Language.h values produce "x has captured the the (faction) keep."~~ fixed
### **Demolishers**
- ~~[[Ram]](http://www.cavernoftime.com/spell=67442) does no damage or knockback. (does on devcore?)~~ (fixed)
- ~~[Hurl Boulder](http://www.cavernoftime.com/spell=68068) should be spell button 1 and Ram should be spell button 2, it's currently swapped. [[video]](https://youtu.be/DmtAzG9S2Z8?t=301)~~ (fixed)
- ~~Hurl Boulder Damage should be roughly 25k before resilience and resistance.~~ (fixed)
- ~~Demolishers spawn in the same place after movement rather than in the original spawn.~~ fixed.
### **Siege Engine**
- ~~Siege engine (workshop) cannot be entered by either faction. deeper issues need to be tested once the vehicle can be entered.[[video]](https://www.youtube.com/watch?v=IcabJ7nvgqg)~~ Fixed
### **(both factions) Gunship Turret**
- ~~Turrets do no damage to alliance gates.~~ fixed
- ~~Turrets do no damage to enemy players.~~ fixed
- ~~Turrets can move forward similar to a demolisher.~~ fixed
- ~~Dismounting a turret while aiming high will dismount you to a location underneath the deck surface.~~ fixed
- ~~Dismounting (or maybe mounting) a turret removes you from the gunship transport state and leaves you falling under the ship on dismount.~~ fixed
- The Alliance gunship turret vehicle has you sitting in the middle of it rather than behind it as you turn. (vehicle 452)
### **Catapult**
- Catapult launch has a static visual trajectory. You always move similar to a heroic leap to the destination, through textures and walls alike. The decision for pathing is actually correct, where a trajectory aimed over a wall will still place you at the correct destination.
### **Glaive Thrower**
- ~~[Glaive Throw](http://www.cavernoftime.com/spell=68827) does no damage to players or gates beyond 150 yards.~~
- ~~[Blade barrage](http://www.cavernoftime.com/spell=69515) does not do damage to players beyond 150 yards.~~
- Glaive throwers do not incline/decline with their surrounding terrain.
- ~~Glaive throwers spawn in a moved location after being destroyed rather than at the original spawn.~~ fixed.

**Comment by Saintagony** [comment]
Catapult throw visual bug. When it launches you, your character should follow the line or the trajectory you've set by the catapult.
It will get you to the landing spot currently but if you aim it over the wall, your character will just get thrown through the wall instead of going over.

**Comment by PN-Cryptid** [comment]
All Vehicle health levels corrected.

**Comment by PN-Cryptid** [comment]
Reference video:
https://www.youtube.com/watch?v=8gwgfz9E0NI

**Comment by Saintagony** [comment]
Can move the gunship turrets off the gunship if you move forward while on a gunship turret

**Comment by PN-Cryptid** [comment]
> Can move the gunship turrets off the gunship if you move forward while on a gunship turret

fixed.

**Comment by Saintagony** [comment]
Playing on alliance side "Huge Seaforium Bombs" stacked outside of the Base.....the far right Seaforium pile will respawn after a longer rate in comparison to the other 3 bomb piles.

**Comment by PN-Cryptid** [comment]
> Playing on alliance side "Huge Seaforium Bombs" stacked outside of the Base.....the far right Seaforium pile will respawn after a longer rate in comparison to the other 3 bomb piles.
> 
> https://youtu.be/TKHdW4HLPK0?t=366
> 4 Guards should walk up to the front door.

fixed the bombs.

**Comment by PN-Cryptid** [comment]
> ### **(both factions) Gunship Turret**
> * ~Dismounting a turret while aiming high will dismount you to a location underneath the deck surface.~ fixed
> * ~Dismounting (or maybe mounting) a turret removes you from the gunship transport state and leaves you falling under the ship on dismount.~ fixed

Fixed

**Comment by PN-Cryptid** [comment]
Siege engine requires work:

https://www.youtube.com/watch?v=PHJCumdMyCk&t=54
https://www.wowhead.com/npc=34776/siege-engine#comments

**Comment by PN-Cryptid** [comment]
> Siege engine requires work:
> 
> https://www.youtube.com/watch?v=PHJCumdMyCk&t=54
> https://www.wowhead.com/npc=34776/siege-engine#comments

fixed.

**Comment by PN-Cryptid** [comment]
Should be able to switch seats while already mounted on siege engine.

Siege Engine turrets should not be mountable till the 3 minute mark.

Siege Engine should dissappear upon base faction change.

**Comment by Saintagony** [comment]
> * Players are dismounted when using portals, but [should not be dismounted.](https://youtu.be/bj2iY29PeB0?t=325)

Fixed

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/bg-isle-of-conquest-r84/
