### ISSUE TITLE
[List] Battleground Queue & Misc

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#286]
**Cross-Faction**

- When you join a battleground as the opposing faction, the faction displayed next to your portrait is not updated.

- ~~When placed into a battleground on the opposing faction, the server may morph players into a race that cannot play their class: Blood elf shamans, tauren rogues, etc.~~

~~In the interest of maintaining a steady feel for battlegrounds, we discussed the idea of setting a default race for each class/race combo that would present as similar of feel as possible, while still presenting a recognizable race/class combination.~~

~~(And the possibility of choosing it yourself somehow)~~ fixed.

![unknown](https://user-images.githubusercontent.com/58305537/96368138-29a16200-1120-11eb-9097-e77bfa431ea6.png)

**BG Queue Integration**

Description:
The random BG queue was a compliment to the invididual BG queues on retail.

Current behaviour:
The random BG queue is a standalone queue that does not involve players from other queues.

Expected behaviour:
- Players queued for WSG specifically should get first priority to join a random BG that starts as WSG.

- Players should be able to queue for multiple BGs if not in the random BG queue.

- Currently Factions cannot engage in same-faction rated battlegrounds.

**War Games**

- ~~war games are currently disabled.~~(Implemented)

**Talent Specialization Change**
- Players should be able to cast change specs during the preparation period of bgs.  [Reference](https://wow.gamepedia.com/Dual_Talent_Specialization) **UPDATE** After deeper research, it appears that packets from the client are not even being sent to the server when a player is in a battleground zone. For the test, every spell hook had been tagged with a TC_LOG and none of them are executed.

**Capturing Bases**
- ~~Capturing bases should trigger a helical aura around the flag. [Shown at 1:30](https://youtu.be/7vVqYAh-wZ8)~~

**Comment by Saintagony** [comment]
https://wowpedia.fandom.com/wiki/Conquest_Points
150 CQ for 1st Random BG of the day.
75 CQ for non rated BG wins from then on.

**Comment by PN-Cryptid** [comment]
https://wowpedia.fandom.com/wiki/Battleground
When queuing for a battleground as a group and a player is unable to join the queue, an error message tells you specifically the name of that player.
Call to Arms is Deactivated

**Comment by PN-Cryptid** [comment]
Helical effect during base capture fixed.

**Comment by PN-Cryptid** [comment]
First Implementation of wargames active.

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/universal-battleground-fix-r83/
