### ISSUE TITLE
[List] Stranglethorn Vale Fishing Extravaganza

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#288]
A. Before the Event:
Sunday at 0000:
- https://www.wowhead.com/npc=15116/grinkle should be spawned
- This quest is repeatable. you can sit here and spam quest completions.https://www.wowhead.com/quest=8228/could-i-get-a-fishing-flier

- Quest not available from Barrus (https://www.wowhead.com/npc=15119/barrus):
https://www.wowhead.com/quest=8229/could-i-get-a-fishing-flier

1h before the event:
- NPCs should spawn as shown, all oriented into a "(" shape, all pointing at the base of the seaweed. 
(they are down by the bank and on the level below this)
https://imgur.com/a/lsTEqb8

B. Start (2 PM server time sundays):
- Quest discovery for everyone in southern or northern stranglethorn: https://www.wowhead.com/quest=8193/grand-prize
- NPC Yell to everyone who got the quest: https://youtu.be/-X-qQ1DdqRo?t=191
- Fish Spots spawn:
- Fishing spots are only spawned on the eastern coast of the cape of stranglethorn. they should be up and down both coasts of both stranglethorn zones.
(https://www.wowhead.com/item=19807/speckled-tastyfish)

C. Grand prize turned in:
- Should announce you as the winner and remove the "Grand Prize" quest from everyone. 
https://youtu.be/-X-qQ1DdqRo?t=310
- Currently is repeatable and has no efffect on the event.

Remainder of the event:
Apprentice Angler:
- Available before "Grand Prize" is turned in.
- [Gold reward is wrong.]( https://www.wowhead.com/quest=8194/apprentice-angler#comments:id=1440106)

- Rare Fish: check to see if these 3 items are rare drops in the tastyfish loot table:
https://www.wowhead.com/item=19803/brownells-blue-striped-racer
https://www.wowhead.com/quest=8224/rare-fish-dezian-queenfish
https://www.wowhead.com/item=19805/keefers-angelfish

D. End
- Despawn all fishing nodes and npcs.

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/stranglethorn-vale-fishing-extravaganza-r94/
