### ISSUE TITLE
[List] Gurubashi Arena Event

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#289]
**QUESTS:**
- Rogue npc should not be spawned before starting.
- Daily quest should not be available before completing the actual quest.
- Daily quest is fleshed out kinda, whereas the normal quest is instant complete.
- Both quests should spawn the rogue NPC visible as a higher healthed and normal damage mob quest objective.

- Currently chest is available every few minutes.
Sequence of events: https://www.youtube.com/watch?v=b5l5Pju2cMg

**NPC: Short John Mithril behavior**
- (2345, 0245, 0545, 0845, 1145, 1445, 1745, 2045) - Yell(to eveyone in the cape of stranglethorn):"The Gurubashi Arena Challenge will begin in 15 minutes!"

- (0000, 0300, 0600, 0900, 1200, 1500, 1800, 2100) - Start 2 minute walk to center of arena, arriving just a few seconds early. Yell(to eveyone in the cape of stranglethorn):"Arrr, Me Hearties! I be havin' some extra Treasure that I be givin' away at the - - Gurubashi Arena! All ye need do to collect it is open the chest I leave on the arena floor!" 

- (0002, 0302, 0602, 0902, 1202, 1502, 1802, 2102) - Yell(to eveyone in the cape of stranglethorn):"Let the bloodletting begin!", Chest is spawned, short john mithril runs for his life back to his sitting spot on the back stands.

- (0025, 0325, 0625, 0925, 1225, 1525, 1825, 2125) - Chest is despawned.

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/gurubashi-arena-event-r95/
