### ISSUE TITLE
Demonology Warlocks Immolation Aura

### ISSUE THREAD

**Issue by Svenmaster1** [ProjectNelth/BugTracker#291]
Description: Immolation aura needs to be redesigned.

Current behaviour: Immolation aura is currently a debuff and not a buff on the warlock. And it does not expire when metamorphosis expires.

Expected behaviour: Immolation Aura should be applied as a buff on the warlock and Expire when metamorphosis expires

Links: https://youtu.be/f__LGzHItyU?t=161  https://imgur.com/a/F6s9Ab5

**Comment by iRadioactive** [comment]
fixed & closed
