### ISSUE TITLE
[Warlock] Dark Intent

### ISSUE THREAD

**Issue by Svenmaster1** [ProjectNelth/BugTracker#292]
Description: Warlocks Dark Intent buff Should be removed from the buffed target if the warlock or the target member leaves the group.

Current behaviour: Sticks to target after leaving group.

Expected behaviour: Should be removed from the target if the player or the warlock leaves the group.

Links:

**Comment by WufcPN** [comment]
After doing research we found that this is false and Dark Intent can be casted on any friendly target player.
https://youtu.be/P65nnTL0dkc?t=5
