### ISSUE TITLE
[Assassination Rogue] Vendetta

### ISSUE THREAD

**Issue by Svenmaster1** [ProjectNelth/BugTracker#295]
Description: Vendetta sticks to the target after switching specc

Current behaviour: Applying Vendetta on a target **AS** Assassination and switch specc to combat or Subtlety the Vendetta debuff will remain on the target and this will make you benefit from Vendetta in the wrong specialization.

Expected behaviour: Vendetta should be removed from the target if you switch to a different specialization

Links:

**Comment by WufcPN** [comment]
Fixed as of this very moment. Hyjarion.
