### ISSUE TITLE
[Minor] Beginner shaman trainer offers high lvl spells

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#296]
Description: Title. Shikrik, the beginner shaman trainer in the Valley of Trials, offers spells Earthbind Totem, Bloodlust, and Rockbiter Weapon, when it should only offer lvl 5 and below spells.

**Comment by therealsmf** [comment]
Applies to all trainers in all of the starter areas other than DK ofc. I mention this in multiple of my low level zone reports, they will be looked at when we get to the point in looking into those.

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/topic/116-starter-zone-class-trainers-rework/
