### ISSUE TITLE
[Quest] Twilight Captivity [25321]

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#302]
Description: As a 'collect 1 of from mob' type quest, the quest item "Twilight Overseer's Key" should be lootable by all group members when dropped.

Current behaviour: Only one group member can loot the key.

Expected behaviour: All group members should be able to loot the key.

Links: https://www.wowhead.com/quest=25321/twilight-captivity

**Comment by Wondii** [comment]
fixed 
13.08.2021
