### ISSUE TITLE
[Quest] Through the Dream [25325]

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#303]
Description: Quest uncompletable.

Current behaviour: Arch Druid Fandral Staghelm NPC that should be escorted out of the cave disappears after a few seconds, preventing completion.

Expected behaviour: NPC should not vanish.

Links: https://www.wowhead.com/quest=25325/through-the-dream

**Comment by therealsmf** [comment]
have you tried walking a bit further, so he "disappears" on top of the dragon? was not an issue when checked initially some months ago

**Comment by Wondii** [comment]
fixed
13.08.2021
