### ISSUE TITLE
Farseer Krogar: Missing Quest

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#304]
Description: Horde NPC Farseer Krogar; unable to receive quests from this NPC. He should have 5 quest(s) that are started by talking to him.

Current behavior: Cannot see or receive any quest from him.

Expected behavior: Should give the following quest(s):
1. Disaster at Mount Hyjal
2. The Call of the World-Shaman
3. The Eye of the Storm
4. The Maelstrom
5. To the Depths
Links: https://www.wowhead.com/npc=45244/farseer-krogar
1. https://www.wowhead.com/quest=49855/disaster-at-mount-hyjal
2. https://www.wowhead.com/quest=29440/the-call-of-the-world-shaman
3. https://www.wowhead.com/quest=28805/the-eye-of-the-storm
4. https://www.wowhead.com/quest=27203/the-maelstrom
5. https://www.wowhead.com/quest=28816/to-the-depths

**Comment by therealsmf** [comment]
4/5 of these are breadcrumbs to the cata zones, and the thrall questline is not scripted yet as far as im aware. i believe it was a staff decision not to waste dev time on these 1 quest breadcrumbs, as the introductory quests as well as the warchiefs command/heros call quests are already on the board if you are level appropriate.
