### ISSUE TITLE
[Quest] [Minor] Lycanthoth the Corruptor [25272]

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#305]
Description: Upon completion of the quest as a group, only 1 party member was teleported. This does not prevent progress as other players can simply move to the next location manually.

Expected behaviour: Every party member should be teleported as they individually complete the quest.

Links: https://www.wowhead.com/quest=25272/lycanthoth-the-corruptor

**Comment by Wondii** [comment]
fixed
13.08.2021
