### ISSUE TITLE
[Quest] Get Me Outta Here! [25332]

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#307]
Description: Escorted NPC disappears after a few seconds, making the quest uncompletable. Player is left with the debuff stating that he is being followed by the NPC, which stays after abandonning the quest and seems to prevent him from spawning again when retaking it.

This is potentially a global issue with escorted NPC, see also https://github.com/ProjectNelth/BugTracker/issues/303

Links: https://www.wowhead.com/quest=25332/get-me-outta-here

**Comment by therealsmf** [comment]
was gossip issue related to having to switch a file for the mythic system. we combined the 2 files since then and both work.
