### ISSUE TITLE
[Quest] A Bird in Hand [25731]

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#308]
Description: Thisalee will sometimes fail to capture Marion Wormwing, leaving the harpy to attack the player while unattackable herself.

If multiple players use the brazier at the same time, it is possible to spawn multiple Marion Wormwing NPCs, causing potential further issues with the capturing segment.

Gossip to execute the harpy once captured fails to do anything, see https://github.com/ProjectNelth/BugTracker/issues/299
Quest uncompletable as a result.

Links: https://www.wowhead.com/quest=25731/a-bird-in-hand

**Comment by therealsmf** [comment]
gossip was fixed, the griefing possibility is an issue however
