### ISSUE TITLE
[Quest] Fact-Finding Mission [25740]

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#309]
Description: NPC Thisalee Crow is sometimes visible at the Shrine of Aviana after taking the quest, allowing an instant turn-in when the player should instead fly to Sethria's Roost.

Issue seems caused by multiple players with the quest being nearby, with only some of them being able to see the NPC, and some not. (Vehicle issue?)

Links: https://www.wowhead.com/quest=25740/fact-finding-mission

**Comment by Wondii** [comment]
fixed 
13.08.2021
