### ISSUE TITLE
[Death Knight] Runes can enter client-sided cooldowns that prevent casting when abilities miss or are dodged/parried

### ISSUE THREAD

**Issue by thebotz** [ProjectNelth/BugTracker#313]
Description: When a death knight ability that costs runes misses or is dodged/parried (except death strike since that consumes runes regardless of landing), the runes that the ability tried to consume will be, on the client only, set to the same as the other rune of that type, while on the server will be refunded. This can cause players to be unable to use abilities they should still have runes for if this fake rune cooldown prevents the client from trying to cast.

Links: https://cdn.discordapp.com/attachments/740305277957701833/776341049329188874/unknown.png
The second rune is on a fake cooldown. Server-side, the second blood rune is ready, but this prevent the clients from being able to cast abilities that would cost a blood rune since it thinks itself unable to do so.

https://cdn.discordapp.com/attachments/740305277957701833/776345570058174464/unknown.png
Normal rune cooldowns in cataclysm. You should never see two runes of the same type moving at the same time.

https://www.youtube.com/watch?v=cPtceBashyw video from try that shows the bug happening and what it does.

**Comment by therealsmf** [comment]
confirmed. the bug "fixes" itself if another ability is cast before the fake cooldown ends. (i do it with horn of winter). my "fixed" blood runes get consumed and not refunded yet again, when my 3rd heart strike fails to land again. so the bug happens on the recording twice, back to back.
