### ISSUE TITLE
Quest: "Hard Falls" issue

### ISSUE THREAD

**Issue by illiji** [ProjectNelth/BugTracker#314]
Description: Quest Hard Falls asks you to kill some stone drakes that the "Opal Stonethrower" npcs are knocking out of the air with rocks.

Current behaviour:
The drakes are getting hit by rocks but just getting stunned and not falling to the ground.
Expected behaviour:
The Stone Drakes should fall to the ground and take damage when hit by one of the rocks. They have some regen out of combat and fly back up once they get back to 100% hp
Links:
https://www.youtube.com/watch?v=zyOnqkZj1aQ&ab_channel=CataQuests

**Comment by LKArthas** [comment]
are on Known Issues mate don't worry doing a workaround for it until i have the propper actin added
