### ISSUE TITLE
Quest: "Resonating Blow" issue

### ISSUE THREAD

**Issue by illiji** [ProjectNelth/BugTracker#315]
Description: rock hopping for quest "Resonating Blow"

Current behaviour:
started the event/fight by using the hammer to hit the big crystal. you get thrown up to the 1st rock and camera focuses like the rock is ground level (making it hard to look around where your character actually is). Everything glitches and character gets stuck when you jump to the next rock
Expected behaviour:
This event/fight has you hopping rock to rock to fight the dragon and avoid her abilities that destroy the rock you're standing on
Links:
https://www.youtube.com/watch?v=ax-jOT1mGYk&ab_channel=CataQuests

**Comment by LKArthas** [comment]
this is anticheat related don't worry dandi is looking into it
