### ISSUE TITLE
[List] Raid Frames

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#319]
- Incoming healing is not being displayed while the option is checked.

![images.jpeg](https://user-images.githubusercontent.com/58305537/102044134-aa788500-3d82-11eb-8024-b761cffda472.jpeg)

References:

https://wow.gamepedia.com/API_UnitGetIncomingHeals

(Need to test)

- commonly on servers, when a player joins your group while you are in combat, your raid frame will *partially* update, leaving you with a a scrambled raid UI including overlapping names and empty raid slots displayed.

**Comment by PN-Cryptid** [comment]
**double toggling the split groups option once you leave combat corrects any scrambling.**

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/raid-frames-r79/
