### ISSUE TITLE
[List] Tol Barad PvP event

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#320]
### Achievements
_Achievements have not been checked yet._

### Functions

- ~~Defending team sees 0/3 towers destroyed when 3 towers have been destroyed and 1 base has been taken.
Defenders **SHOULD** see towers taken as well as the attackers.~~ fixed

References:
https://youtu.be/LKHYFCRtad4

**Comment by therealsmf** [comment]
achievements are global - everything else fixed - closing
