### ISSUE TITLE
Frost Armor 

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#325]
Description: Currently causes slow on enemy when non-physical spells harm the mage, when it shouldn't. Example spells like Heroic Throw and Judgement that aren't physical are causing the player to be slowed.

Current behaviour: Slows enemy when attacked by non-physical spells.

Expected behaviour: Should only slow physical damage spells.

Links:
https://www.youtube.com/watch?v=adeol-Io-Ho&t=24s   22 Seconds in.
https://www.youtube.com/watch?v=AYpuoLjnqU0             39 Seconds in.

**Comment by therealsmf** [comment]
correction: frost armour should not trigger on ranged or non-physical attacks, such as heroic throw and judgement.

**Comment by PN-Cryptid** [comment]
Fixed

**Comment by PN-Cryptid** [comment]
This video was not valid evidence, but a more recent video has been found:
https://www.youtube.com/watch?v=4DYivalvwdU
