### ISSUE TITLE
[List] Dalaran Arena

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#330]
Description: Water that pushes you out of starting room toggles anti-cheat for speed hacking, will teleport you back into starting room then kick you out again.
Reference:
https://www.youtube.com/watch?v=E81DwC2Jt40 1:18 You'll see where he lands when getting knock backed, currently knock back looks like it  is about half the length roughly.

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/dalaran-arena-anticheat-r93/
