### ISSUE TITLE
[Item] Loot-A-Rang

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#331]
Current behaviour: Currently spawns a random button object that does nothing and cannot be clicked, still have to normally loot object.

Expected behaviour: Should cast Spell=84342 which has a 40 yard range and loots the target.

Links: https://www.youtube.com/watch?v=-QaImGgO8QA

**Comment by Akka3223** [comment]
**It is indeed a bug, video - https://streamable.com/0ngdwi**

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/item-loot-a-rang-r81/
