### ISSUE TITLE
Warlock Castable buffs

### ISSUE THREAD

**Issue by Svenmaster1** [ProjectNelth/BugTracker#332]
Description: Castable buffs(friendly) Dark Intent & Unending Breath makes pets walk towards the target as if its going to attack then walks back to the owner.

Current behaviour: Pet walks towards the target a short distance and then walks back when you buff

Expected behaviour: Shouldnt walk towards the friendly target when i buff.

Links:

**Comment by Saintagony** [comment]
> Description: Castable buffs(friendly) Dark Intent & Unending Breath makes pets walk towards the target as if its going to attack then walks back to the owner.
> 
> Current behaviour: Pet walks towards the target a short distance and then walks back when you buff
> 
> Expected behaviour: Shouldnt walk towards the friendly target when i buff.
> 
> Links:

+Only happens when pet is on Assist.

**Comment by PN-Cryptid** [comment]
fixed.
