### ISSUE TITLE
[Spell] Searing Totem

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#335]
Description: Searing totem should switch targets to whichever target has flame shock/stormstrike effect.

Current behavior: Keeps attacking initial target whether it had flame shock or not and won't switch to the new target that has flame shock/stormstrike even if it expired from the original target and was moved to a new target.

Expected behaviour: Should switch to the target with flame shock/stormstrike on it.

Links: https://www.wowhead.com/spell=3599/searing-totem#changelog *Search through changelog tabs and you'll see in 4.2 "The totem will prefer to target enemies that are afflicted by your flame shock or stormstrike effects."

**Comment by therealsmf** [comment]
doesnt switch automatically, it works as intended if you redrop the totem.
