### ISSUE TITLE
Mend Pet

### ISSUE THREAD

**Issue by therealsmf** [ProjectNelth/BugTracker#337]
Description: Hunter spell Mend Pet (spellid 136) does not have a 45 yard range limit when the player has no target selected.

Current behaviour: The hunter's pet can be healed from any range.

Expected behaviour: Hunters should not be able to heal their pet when it's more than 45 yards away from them.

Links:
![WoWScrnShot_011221_152637](https://user-images.githubusercontent.com/66882878/104326999-a14a1780-54ea-11eb-9ef4-ddd2316d8d59.jpg)

**Comment by PN-Cryptid** [comment]
fixed.
