### ISSUE TITLE
Transmute: Living Elements

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#338]
+Mount Hyjal: Volatile Fire
+Vashj'ir: Volatile Water
+Deepholm: Volatile Earth
+Uldum: Volatile Air

Current behaviour:
Currently it's random and being in a Cataclysm Zone still makes the Transmute random.
Expected behaviour:
Transmuting the Volatile Life while in a Cataclysm Zone should change into an expected Volatile based on the zone.
Links:
https://www.bluetracker.gg/topic/us-en/1406721952-transmute-living-elements-clarification/
https://wow.gamepedia.com/Transmute:_Living_Elements

**Comment by Akka3223** [comment]
**Confirmed - https://i.imgur.com/whewgnh.jpeg**

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/transmute-living-elements-r77/
