### ISSUE TITLE
Fury: Dual Wield

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#341]
Description:
Allows the warrior to wield a weapon in their off-hand. Increases damage of offhand weapons by an additional 25%.

Current behaviour:
Auto-attacks are double-dipping the 0.75 multiplier for a 0.56 multiplier.
Spells are benefitting from a multiplicative version of the 25% (0.50 * 1.25 = 0.625) rather than additional (0.50 + 0.25 = 0.75).

Expected behaviour:
Autoattacks and spells from your offhand should produce 75% of the mainhand damage.

spells:
![image](https://user-images.githubusercontent.com/58305537/106399474-d01b2580-63e6-11eb-85d8-3261dedcc771.png)

auto attacks:
![image](https://user-images.githubusercontent.com/58305537/106399497-f214a800-63e6-11eb-83a4-ae44145f123f.png)

**Comment by therealsmf** [comment]
affected spells are raging blow and slam (with single minded fury).
the 0.56 is the effect of the double dip (0.75^2=0.5625) for autos.

**Comment by PN-Cryptid** [comment]
Fix submitted, pending testing.
