### ISSUE TITLE
Hour of Twilight Dungeons: Item Level Requirements

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#342]
Description:
Well of Eternity, End Time, Hour of Twilight

Current behaviour:
Well of Eternity requires 378.
End Time requires 353.
Hour of Twilights requires item level 365.

Expected behaviour:
All three dungeons should require item level 353.

**Comment by Akka3223** [comment]
**Confirmed https://imgur.com/a/KZjvf56**
