### ISSUE TITLE
Warlock Affliction Talent Pandemic

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#345]
Description: Pandemic 2/2, Drain Soul has 100% chance to refresh the duration of Unstable Affliction when dealing damage on targets below 25%.

Current behaviour: Doesn't refresh the duration of Unstable Affliction.

Expected behaviour: Should refresh the duration of Unstable Affliction.

**Comment by therealsmf** [comment]
it refreshes on ticks of drain soul damage, not when you start channeling. the first tick isnt instant, thus the refresh isnt either.

**Comment by therealsmf** [comment]
tested on qa/dev realm 02.08.
