### ISSUE TITLE
[List] Eye of the Storm (Rated)

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#349]
### Achievements
_Achievements have not been checked for this battleground_

### Mechanics
- ~~World states are empty~~(fixed)
- ~~Passing 1400 points prints an error string.~~(fixed)
- ~~Banners are off-center from their posts~~(fixed)
- ~~Flag pickup event plays no sound~~(fixed)
- ~~Flag capture event plays no sound, shows no notification, grants no honor, grants no extra points.~~(fixed)

~~**Rated EOTS will be disabled for the time being.**~~(fixed)

**Comment by PN-Cryptid** [comment]
Should be fixed:
Passing 1400 points prints an error string.
Flag pickup event plays no sound

**Comment by PN-Cryptid** [comment]
All known issues with rated Eye of the Storm have been resolved and the battleground has been returned to the rated BG queue.

**Comment by PN-Cryptid** [comment]
The wrong noise is played when the flag gets respawned after capping.

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/eye-of-the-storm-r91/
