### ISSUE TITLE
Guild Herald Companion

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#350]
Description: Guild herald companion is supposed to hold guild flag, currently holds nothing.

Links:
https://www.wowhead.com/item=65364/guild-herald#screenshots:id=232005

**Comment by PN-Cryptid** [comment]
partially fixed. the banner does not show the correct icon.

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/guild-herald-companion-banner-does-not-show-the-correct-icon-r82/
