### ISSUE TITLE
Guild Weekly Cap not Limited

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#355]
Description: Should have a weekly cap limite of 4375.

Current behaviour: Keeps going past the 4375 limit - (Atleast with multiple arena wins it keeps going at 1230+ guild rep per win)

**Comment by therealsmf** [comment]
can you provide a screenshot hovering over the guild rep bar in the default guild tab?

**Comment by Saintagony** [comment]
+Before Photo
![WoWScrnShot_062321_135224](https://user-images.githubusercontent.com/67765647/123167467-6c43d880-d42b-11eb-8065-ecaaf0462100.jpg)

+Winning you receive 1232
![WoWScrnShot_062321_135348](https://user-images.githubusercontent.com/67765647/123167497-7534aa00-d42b-11eb-9b12-14d7b31864fa.jpg)

+Says you received 308 from the one win and will keep adding after each win.
![WoWScrnShot_062321_135407](https://user-images.githubusercontent.com/67765647/123167506-7a91f480-d42b-11eb-9c94-0f84d68d303e.jpg)

+Points after two wins
![WoWScrnShot_062321_135635](https://user-images.githubusercontent.com/67765647/123167531-854c8980-d42b-11eb-81c0-997e3a1ce4fe.jpg)

**Comment by therealsmf** [comment]
all i see is the actual amount of rep gained vs what gets accounted for in the weekly cap is not aligned, those values might be wrong as well but thats a different issue. can you also check if it actually goes past the weekly 4375 cap?

**Comment by Saintagony** [comment]
Ah the conversions is just different and weird I suppose. It does stop the cap at the weekly limit technically but the cap per win will start off at 308(on guild "This week" tab) 1232(on guild "Current" tab)then change after a certain amount of wins to a lower number until eventually you just received a 14,000+ reputation in the weekly cap limit of 4375.

**Comment by therealsmf** [comment]
so that would mean the weekly cap is actually 17500 (4375 times 4), but the visuals for it are not affected by the boost (kinda like a tooltip). also means that the actual cap will always be boosted by the amount we are gonna have (still TBD if we change it from x4 rep rates), so unsure if we can do anything about it.
