### ISSUE TITLE
Pre-match wait timer

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#357]
Description:
![image](https://user-images.githubusercontent.com/58305537/124367649-3a9af080-dc27-11eb-8fb1-8b76fe9b6d19.png)

![image](https://user-images.githubusercontent.com/58305537/124367641-13dcba00-dc27-11eb-8182-610baae8feae.png)

Current behaviour:
timer bars are always getting lower and lower, likely because old ones do not get removed.

Expected behaviour:
pre-match timers should be in the same place over and over again.
Links:

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/pre-match-wait-timer-r80/
