### ISSUE TITLE
Warlock Talent: Demonic Pact

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#358]
Description:
+ Should only be active when there's a point put into it.
It currently will stay active if you summon a felguard in Demonology spec, then switch talents and summon felhunter.
![WoWScrnShot_071021_035717](https://user-images.githubusercontent.com/67765647/125156424-4c9ef680-e133-11eb-9d17-f7f61971d8ee.jpg)

**Comment by therealsmf** [comment]
could you try reproducing again on a fresh character? i was not able to replicate: 
https://www.youtube.com/watch?v=Qfl4xiAjs5E

**Comment by Saintagony** [comment]
Guess it must've just been a cache issue cause I'm unable to replicate it now for some reason so I'm going to assume it was that. My bad...
