### ISSUE TITLE
Partiarch's Blessing - floaty bug

### ISSUE THREAD

**Issue by UsedSeat** [ProjectNelth/BugTracker#360]
Description: I canceled the Cinematic and my character got stuck, floating in the air. /Reload doesn't resolve it. Re-logging brought me back to the quest giver and I can move my character again. 

Current behaviour: Floaty char

Expected behaviour: Not floaty char

Links: 
[img]https://i.imgur.com/pNjyAUu.png[/img]

**Comment by therealsmf** [comment]
never experienced this in my 5+ runthroughs, are/were you using miniclient?

**Comment by UsedSeat** [comment]
I think I might be, since the download took forever for the full client as i remember.. not 100% sure though.

________________________________
Fra: therealsmf ***@***.***>
Sendt: 25. juli 2021 01:11
Til: ProjectNelth/BugTracker ***@***.***>
Cc: UsedSeat ***@***.***>; Author ***@***.***>
Emne: Re: [ProjectNelth/BugTracker] Partiarch's Blessing - floaty bug (#360)


never experienced this in my 5+ runthroughs, are/were you using miniclient?

**Comment by therealsmf** [comment]
interesting. can you try to recreate this with like 10 attempts at force adding/removing the quest with commands
.quest add 24679
.quest remove 24679
and see if it happens again while cancelling the cutscene at different points?

**Comment by UsedSeat** [comment]
First try and im stuck more or less at the same exact spot in the air.. this time in 'travel form' as a druid..

hm

________________________________
Fra: therealsmf ***@***.***>
Sendt: 25. juli 2021 17:44
Til: ProjectNelth/BugTracker ***@***.***>
Cc: UsedSeat ***@***.***>; Author ***@***.***>
Emne: Re: [ProjectNelth/BugTracker] Partiarch's Blessing - floaty bug (#360)


interesting. can you try to recreate this with like 10 attempts at force adding/removing the quest with commands
.quest add 24679
.quest remove 24679
and see if it happens again while cancelling the cutscene at different points?

**Comment by Wondii** [comment]
dismount and cancel any shapeshifts.
