### ISSUE TITLE
[Quest][Mount Hyjal] Mental Training: Speaking the Truth to Power 

### ISSUE THREAD

**Issue by Wondii** [ProjectNelth/BugTracker#363]
Description: The quest is autocomplete at the moment. Needs core support. 

  My notes:
  Item: 52828: Orb of Ascension 
	  ID - 73984 Mental Training -> summons npc=39601/orb-of-ascension

  ID - 73982 Yes  
	  Trigger spell (74010) Answer Yes Correct.	    //  Caster Aura Spell (74008) Answer the Question! 
  	  Trigger spell (74011) Answer Yes Incorrect	    //  Caster Aura Spell (74009) Answer the Question! 

  ID - 73983 No
	  Trigger spell (74012) Answer No Correct  		//   Caster Aura Spell (74009) Answer the Question!
	  Trigger spell (74013) Answer No Incorrect 		//   Caster Aura Spell (74008) Answer the Question!

  IMO aura 74008 and 74009 are controller of answers

  ID - 76643 Dismiss Orb of Ascension - aoe ping to orb

Links: 
https://www.wowhead.com/quest=25299/mental-training-speaking-the-truth-to-power
https://wowpedia.fandom.com/wiki/Mental_Training:_Speaking_the_Truth_to_Power

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/list-existing-quest-related-bugs-in-starterend-zones-r98/
