### ISSUE TITLE
[Quest][Mount Hyjal] Graduation Speech

### ISSUE THREAD

**Issue by Wondii** [ProjectNelth/BugTracker#364]
Description: The quest is autocomplete at the moment. Needs core support.

My notes:
ID - 74948 Twilight Speech
	Trigger spell (94441) Twilight Speech Linked Aura [INTERNAL]

-- spells on bar
ID - 74934 Inspire! dummy ping crowd 18,8 
	Trigger spell (74961) Inspiration.  77 (SPELL_EFFECT_SCRIPT_EFFECT)

ID - 74935 Incite!  dummy ping crowd 18,8 
	Trigger spell (74963) Divisiveness 	77 (SPELL_EFFECT_SCRIPT_EFFECT)

ID - 74937 Pander! 	dummy ping crowd 18,8 
	Trigger spell (74962) Crazy 	77 (SPELL_EFFECT_SCRIPT_EFFECT)

ID - 74947 Step Down (Aura removal)
	Trigger spell (74948) Twilight Speech. 

ID - 74966 Ping
	 Trigger spell (74962) Crazy. 

Crowd npc ids: 
Twilight Initiate 	40185
Twilight Guard 		39828

ObjectID: 202996 Initiation Podium 

Links:
https://www.wowhead.com/quest=25315/graduation-speech
https://wowpedia.fandom.com/wiki/Graduation_Speech

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/list-existing-quest-related-bugs-in-starterend-zones-r98/
