### ISSUE TITLE
[Quest][DK Zone] The Light of Dawn

### ISSUE THREAD

**Issue by Wondii** [ProjectNelth/BugTracker#365]
Description: Low quality core scripts. Need touch.

// try's notes
the mobs just keep dying and respawning, they should probably have a lot more health and last for the entire fight (5 mins after "pulling" iirc)
lightbeam and "electricity" visuals are already present at the start and throughout the fight.
the "electricity" should only appear for a few seconds after the fight is "over" and the RP session begins (tirion appears). (this is what should make the fight stop.)
the lightbeam should only appear after tirion frees himself from the lich kings grasp in the RP after. 
the npcs continue to cast spells on eachother even after the fight was supposed to end.
reference: https://www.youtube.com/watch?v=8ekrr2JZfZM

Links:
https://wowpedia.fandom.com/wiki/The_Light_of_Dawn_(quest)
https://www.wowhead.com/quest=12801/the-light-of-dawn

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/list-existing-quest-related-bugs-in-starterend-zones-r98/
