### ISSUE TITLE
[Quest][Mount Hyjal] As Hyjal Burns - Smooth flight

### ISSUE THREAD

**Issue by Wondii** [ProjectNelth/BugTracker#366]
Description: 
The quest is working, but dragon's flight path has sharp turns which sai cant fix.
To make the path smoother the npc script must be created in core (currently in SAI)

try's video: https://youtu.be/7WcJoJah3BQ?t=67

Links:
https://www.wowhead.com/quest=25316/as-hyjal-burns
https://wowpedia.fandom.com/wiki/As_Hyjal_Burns

**Comment by therealsmf** [comment]
also true for deepholm intro quest when the wyvern flies the player down from the maelstrom into deepholm.

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/list-existing-quest-related-bugs-in-starterend-zones-r98/
