### ISSUE TITLE
Dragonwrath Duplication of Arcane Blast Debuff

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#369]
An arcane mage's  [Arcane Blast] will apply another stack of its Arcane Blast debuff upon duplication.

Currently only gains 1 debuff even when it's duplicated.

Also same for frost mage, a frost mage's  [Ice Lance] will consume a second stack of  [Fingers of Frost], upon duplication.

https://wowpedia.fandom.com/wiki/Dragonwrath,_Tarecgosa%27s_Rest

**Comment by therealsmf** [comment]
looks like these things are all broken:

_The duplicated spell is independent of its source spell. The source spell may crit while the duplicate hits or vice versa._ - havent got a single crit from the proc damage

_An arcane mage's  [Arcane Blast] will apply another stack of its debuff upon duplication._

_A fire mage with  [Master of Elements] will find, that a duplicated spell critical will refund mana even though it did not cost any mana._ - dupe spell cant crit, so couldnt test

_A frost mage's  [Ice Lance] will consume a second stack of  [Fingers of Frost], if one is present, upon duplication._

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/dragonwrath-procs-r97/
