### ISSUE TITLE
Priest Expansive Mind

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#370]
Description: Priest power word shield and Prayer of Mending spell(Initial cast, not per tick) should proc Expansive Mind from Heart of the Unliving trinket.
Links: **https://www.wowhead.com/item=77199/heart-of-unliving#comments:id=1621182**

**Comment by therealsmf** [comment]
merging with https://forum.projectnelth.com/bugtracker/expansive-mind-procs-r65/
