### ISSUE TITLE
[Spell] Serpent Sting

### ISSUE THREAD

**Issue by Catyluss** [ProjectNelth/BugTracker#371]
Description: Survival Hunter talent "Serpent Spread" applies serpent sting on the target for 6-9 seconds depending on talent points. A cobra shot should "increase" the duration of Serpent Sting on the target by 6 seconds. 

Current behavior: Multi-shot applies a spell id Serpent Sting that doesn't have its duration increased by Cobra Shot. Only the variation of the Single Target spell id Serpent Sting applies the dot that has its duration increasable by a Cobra shot.

Expected behavior: The Serpent Sting applied from the Multi-Shot should have its duration increased by 6 seconds with a Cobra Shot.

Links: https://youtu.be/UNn_jat-kyA?t=326
In the video given it also showcases the dot going above the 15s base of the Single target Serpent Sting. It also appears that casting a Multi-Shot after it passes the 15s duration mark, it doesn't reset it to the initial talent point dependent duration of the Multi-Shot variation of Serpent Sting.

**Comment by PN-Cryptid** [comment]
fixed

**Comment by therealsmf** [comment]
![image](https://user-images.githubusercontent.com/66882878/132951480-6c08f359-9e62-47bd-aa7e-ee1a11081118.png)
not quite. status as of 9/11
