### ISSUE TITLE
[NPC] Thrall

### ISSUE THREAD

**Issue by Catyluss** [ProjectNelth/BugTracker#373]
Description: Once you reach "The Maelstrom" after defeating the Spine of Deathwing, interacting with the Thrall NPC is meant to queue a discussion between Thrall and The Aspects, where thrall talks before you are able to pull the boss.
**npc_ds_thrall_madness**
Current behaviour: The NPC is instantly giving the option to start the encounter.

Expected behaviour: The NPC should start an RP conversation.

Links: https://youtu.be/K-bbi_HIzes?t=563 (The RP is visible in the chat frame, which after they start the encounter.)

**Comment by therealsmf** [comment]
correction: yell text for voicelines potentially missing on madness pull

**Comment by therealsmf** [comment]
currently:

Thrall yells: It is done; at last the Destroyer has met his end. Now, we can begin to heal our world. - happens right after spine is over and the players get teleported to the madness platforms.

alextrasza yell - you have accomplished the impossible..... - missing entirely

alextrasza yell - before you is the cache of aspects.... - missing entirely

nozdormu yell - ...although we may have to hurry. - missing entirely

Deathwing yells: You have done NOTHING. I will tear your world APART. - happens on madness pull

Ysera yells: I will bring you closer to the Emerald Dream. Seek safety there when the fight becomes too intense. - happens on madness pull

how it should be: 

https://wowpedia.fandom.com/wiki/Madness_of_Deathwing#Intro

![image](https://user-images.githubusercontent.com/66882878/144319606-d79620b4-1037-4025-91fe-58407306b628.png)

the highlighted lines should also appear in the chat (did not check voice as i play with sound off)

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/madness-of-deathwing-intro-rp-lines-missing-r99/
