### ISSUE TITLE
Pets in Sota

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#377]
If you summon pet below decks on the boats, they will stay on the boat, but if you walk up to the ground level your pet will fall off the boat.
Anywhere else on the boat also makes your pet fall through the boat.

The problem with this is for classes with pets. They will have to summon the pet right as they get to shore when the enemy team is already attacking them.

**Comment by therealsmf** [comment]
moved to and merged with 
https://forum.projectnelth.com/bugtracker/bg-strand-of-the-ancients-r88/
