### ISSUE TITLE
[Quest][Bloodmyst Isle] Ending Their World - Escort

### ISSUE THREAD

**Issue by Wondii** [ProjectNelth/BugTracker#378]
Description: 
Quest: https://ptr.wowhead.com/quest=9759/ending-their-world

ive changed quest objectives temporary.

Escort event is skipped due of amount of work to spend to script this quest.
Correct fix in the future.

**Comment by Novaveteran** [comment]
Quest possible to complete, probably a bit tricky since there are a bunch of elites going up the mountain without the help NPC.
Also the mob you are killing seems to be a tad off script wise, supposed to get bigger in size etc. check vid at time stamp.

https://youtu.be/uE0vSRGYaUI?t=859

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/list-existing-quest-related-bugs-in-starterend-zones-r98/
