### ISSUE TITLE
[Flight Master] Exodar - Stephanos <Hippogryph Master> 

### ISSUE THREAD

**Issue by Wondii** [ProjectNelth/BugTracker#379]
Description: 
[Stephanos <Hippogryph Master>](https://ptr.wowhead.com/npc=17555/stephanos) does not show flight connections, just strange node text 
https://gyazo.com/49f88a6a15d0fe79fb7107f5c78b1749

also flight map is bugged for [Zaldaan (Azuremyst Isle)](https://ptr.wowhead.com/npc=43991/zaldaan) and [Laando (Bloodmyst Isle](https://ptr.wowhead.com/npc=17554/laando)

https://gyazo.com/fdcd962e5eca99be0849d672abce7b93
https://gyazo.com/9cf26e89d9e5ff6adf8d23f75da746d2

Notes:
I noticed, the exodar flight master was moved in 4.0.3
Cataclysm Patch 4.0.3a (2010-11-23): Moved from the front gates to the Seat of the Naaru. 
so probably we have out of date data in the core (from WOTLK)

might be related: https://github.com/TrinityCore/TrinityCore/issues/12832

**Comment by therealsmf** [comment]
merged and moved to https://forum.projectnelth.com/bugtracker/list-existing-quest-related-bugs-in-starterend-zones-r98/
