### ISSUE TITLE
Enhancement Shaman 

### ISSUE THREAD

**Issue by Zupcanik** [ProjectNelth/BugTracker#381]
Description: flametongue weapon (shaman weapon enchant) buff (unleash flame) after using Lava Lash (which is fire dmg ) skill doesnt disappear and it should after fire damage skill is activated 

Current behaviour: flametongue buff (unleash flame) activated with unleashed elements doesnt disappear after using Lava Lash (fire skill) and doesnt give extra dmg

Expected behaviour: flametongue buff activated with unleashed elements skill should give extra dmg to every fire dmg skill in this case Lava Lash too 

Links: https://www.wowhead.com/spell=60103/lava-lash

https://wowwiki-archive.fandom.com/wiki/Flametongue_Weapon

https://wowpedia.fandom.com/wiki/Unleash_Flame

https://wowwiki-archive.fandom.com/wiki/Unleash_Flame

**Comment by therealsmf** [comment]
https://www.icy-veins.com/forums/topic/102-unleash-elements-and-lava-lash/

https://web.archive.org/web/20120812121222/https://www.wowhead.com/spell=73683

https://youtu.be/Ew_JeMFUN1g?t=419
