### ISSUE TITLE
BM Hunter spell Widow Venom

### ISSUE THREAD

**Issue by WufcPN** [ProjectNelth/BugTracker#382]
Description: It currently lasts for 30 seconds on both PVE and PVP targets. It should only last for 10 seconds against players. 
30 seconds in PVE.
10 seconds in PVP.

Links: https://youtu.be/b1jk5nxa2nU?t=74

**Comment by therealsmf** [comment]
not a bm hunter specific spell just for the record, also couldnt find patch notes such as for wound poison etc.
Wrath of the Lich King Hotfix (2009-02-18): Wound Poison now has a PvP duration of 10 seconds.
going off purely off the video above.

**Comment by WufcPN** [comment]
Fixed, will be applied next update.
