### ISSUE TITLE
Windwalk weapon enchant

### ISSUE THREAD

**Issue by Zupcanik** [ProjectNelth/BugTracker#383]
Description:Windwalk weapon enchant doesnt work

Current behaviour:Windwalk weapon enchant doesnt work

Expected behaviour: Should aactivaate when attaacking enemy

Links:https://www.wowhead.com/item=52775/enchant-weapon-windwalk

**Comment by therealsmf** [comment]
https://cdn.discordapp.com/attachments/740305277957701833/904420552154951790/World_of_Warcraft_2021-10-31_18-22-54.mp4
