### ISSUE TITLE
[Improved Steady Shot] (confirmed broken)

### ISSUE THREAD

**Issue by WufcPN** [ProjectNelth/BugTracker#384]
Description:  

Current behaviour: [Improved Steady Shot] when i use steady shot > change aspect > steady shot it wouldn't give me the buff of  [Improved Steady Shot]

Expected behaviour: 2:15 you can see he had aspect of fox used steady shot  then swap to aspect of hawk and another steady shot and still got the talent  [Improved Steady Shot] , which is not the case on neltharion

Links: https://youtu.be/BKhfPR2iahs?t=133

**Comment by therealsmf** [comment]
changing aspects seem to break the cycle and start counting, possibly because it checks for all spells casted by the hunter instead of *damaging* spells.
