### ISSUE TITLE
Glyph Of Swiftmend

### ISSUE THREAD

**Issue by Lavjuu** [ProjectNelth/BugTracker#385]
Description: Glyph of Swiftmend

Current behaviour: Glyph of swiftmend should take away that u dont need rejunevation/regrowth to use Swiftmend but even with glyph on it still requirs them.

Expected behaviour:

Links:

**Comment by therealsmf** [comment]
wrong.

glyph of swiftmend causes the effect to not consume the already existing hots on the target. it is still a requirement of the spell to be cast with or without.
