### ISSUE TITLE
Shadow Word: Death

### ISSUE THREAD

**Issue by rradman** [ProjectNelth/BugTracker#386]
Description:
When getting **Polymorphed** by a mage, I should not be able to break it with **Shadow Word: Death** if I have a **Power Word: Shield** on me, or some other shield that absorbs damage, and yet it does break.

Current behaviour:
Poly breaks from SWD.

Expected behaviour:
Damage should get absorbed by the shield and not break the Poly.

**Comment by WufcPN** [comment]
False. SWD is a very special case, and was a very important topic.
(2011 retail) 
https://www.mmo-champion.com/threads/1000618-CC-s-now-count-on-damage-absob

"Spells which have an effect broken by taking damage past a threshold (Entangling Roots, Fear, Frost Nova, etc.) now count damage that was prevented by damage absorbs or other damage reducing effects." This is a blue post.
