### ISSUE TITLE
Masochism

### ISSUE THREAD

**Issue by Saintagony** [ProjectNelth/BugTracker#387]
Description: Should gain 10% of mana from damaging self with Shadow Word Death (SWD).

Current behaviour: Only gain 10% mana from >10% health loss, but does not apply mana gain from SWD spell.

Expected behaviour: Should gain 10% mana after damaging self with SWD.

Links: https://www.cavernoftime.com/spell=89007
Talent: When you take a damaging attack equal to or greater than 10% of your total health, or you damage yourself with your Shadow Word: Death, you instantly gain 10% of your total mana.

**Comment by therealsmf** [comment]
![image](https://user-images.githubusercontent.com/66882878/139922687-a6a78b24-e4ff-4041-b519-4f071c68a11b.png)
works for me
