### ISSUE TITLE
Mor'shan Defense

### ISSUE THREAD

**Issue by omegaroll** [ProjectNelth/BugTracker#4]
Description: 5 Ashenvale Skirmishers/bowmen Slain

Current behaviour: The Ashenvale Skirmishers/bowmen are dead on the ground but you can still attack them. They have 0 HP but you can still do damage till they die.

Expected behaviour: They should be standing up with full HP.

Links: https://www.wowhead.com/quest=13612/morshan-defense

**Comment by PN-Cryptid** [comment]
Fixed. Also added waypoints to have ashenvale skirmishers charge at the gates to die.
