### ISSUE TITLE
[Item= lvl 80 Hierloom unequipable after Max level]

### ISSUE THREAD

**Issue by Xerlene** [ProjectNelth/BugTracker#44]
Description: Hierloom upto lvl 80 are unequipable @ max[85] lvl  . I was just wondering! some people will want to use the Hierloom even @ 85. like [inherited insignia of the alliance]

Current behaviour: Unequipable at level 85

Expected behaviour: Should be able to equip it even after max lvl[85].

Links:

**Comment by omegaroll** [comment]
Not all heirlooms go up to level 85. I don't think this is a bug.

**Comment by Xerlene** [comment]
What i mean is wrath hierloom which go upto lvl 80 r unequipable @ max lvl

Cata hierloom are working fine

**Comment by Ovahlord** [comment]
That's blizzlike. Heirlooms become useless after hitting level 80.

**Comment by Xerlene** [comment]
Lol first time i knew that !! I only ply in private server so idk how retail hierloom works !!
