### ISSUE TITLE
Random dialog window 

### ISSUE THREAD

**Issue by lillemand13** [ProjectNelth/BugTracker#46]
Description: random dialog windows open when you fly over SW

Current behaviour:^^^^

Expected behaviour: not opening 
![fail](https://user-images.githubusercontent.com/57834650/69759379-3d3b8700-1162-11ea-9285-d8790c0777b1.PNG)

Links:

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/random-dialog-window-r71/
