### ISSUE TITLE
Inkeeper bug

### ISSUE THREAD

**Issue by Xerlene** [ProjectNelth/BugTracker#54]
Description:Inkeeper MaeganTillman From Old Town

Current behaviour: Can't make inn

Expected behaviour: Should be able to make inn

Links: https://www.wowhead.com/npc=44237/maegan-tillman

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/maegan-tillman-innkeeper-from-old-town-can-not-set-hearthstone-location-r72/
