### ISSUE TITLE
Quest: Sacrifices

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#60]
Description: 
Quest progression is based on worgen killed rather than aggro'd.

Current behaviour: 
Quest progression is granted for killing worgen.

Expected behaviour: 
While riding the horse, quest should be progressed by aggroing worgen.

Links:
https://www.wowhead.com/quest=14212/sacrifices

**Comment by therealsmf** [comment]
core issue - vehicles and combat dont mix well together, we currently have the torch oneshotting them and credit is given on death instead of aggro.

**Comment by therealsmf** [comment]
moved to https://forum.projectnelth.com/bugtracker/quest-sacrifices-14212-quest-progression-is-based-on-worgen-killed-rather-than-aggrod-r73/
