### ISSUE TITLE
Dungeon/spell bug

### ISSUE THREAD

**Issue by lillemand13** [ProjectNelth/BugTracker#63]
Description: Charge bug in Razorfen downs

Current behaviour: If you charge Mordresh Fire ey you will charge under ground and get stuck 

Expected behaviour: Dont run under ground 
![Capture](https://user-images.githubusercontent.com/57834650/69825993-872f7600-1211-11ea-919f-5f29ca996217.PNG)

Links:

**Comment by Goztoc** [comment]
Not related to the dungeon - charge pathing.
