### ISSUE TITLE
WOE illidan Buff bugg

### ISSUE THREAD

**Issue by Xerlene** [ProjectNelth/BugTracker#68]
Description:On Woe illidan buff  Shadow walk which grant 100%crit instantly dissapear

Current behaviour: Buff not working instantly dissapear

Expected behaviour: Should grant 100%crit for 30sec Max stack

Links:https://www.wowhead.com/spell=103020/shadow-walk

**Comment by therealsmf** [comment]
should be reported in the big dungeon reports. if the issue still exists after changes, reopen on the forum :)
