### ISSUE TITLE
Faction Change

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#71]
Description: Changes Faction

Current behaviour:
Allows most recent "new" race racial effects to stack with original race racials.
-Only original and most recent race racial effects will stack. I tried stacking all racials and it did not work.

Expected behaviour:
original race racial effects should be removed at faction change.

Links:
![image](https://user-images.githubusercontent.com/58305537/70397106-42f46080-19dd-11ea-9361-2d10f374333a.png)

**Comment by cryptid123** [comment]
This seems to only be with worgen, likely because the racial spells are learned after character creation.

**Comment by PN-Cryptid** [comment]
fixed.
