### ISSUE TITLE
Flight Form/Mount --> druid forms

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#72]
Description:
players should be able to transfer to other forms while in flight form.
Current behaviour:
Players cannot shift into a druid form while flying above the ground.
Expected behaviour:
Players should be able to abandon flying mounts/forms mid-air for druid forms.
Links:

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
