### ISSUE TITLE
[Quest] More skulls for brew

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#78]
Description:
Collect 20 
Current behaviour:
The quest ignores skulls in your bag and does not allow you to proceed.
Expected behaviour:
The quest should recognize that you have 20 skulls in your bag and allow for the quest to be turned in.
Links:
https://www.wowhead.com/quest=12718/more-skulls-for-brew
![image](https://user-images.githubusercontent.com/58305537/70461999-f87bee00-1a87-11ea-8de7-2346aea63c53.png)

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
