### ISSUE TITLE
Glyph of resilient grip

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#79]
Description:
Reset the CD on Death Grip if it fails due to an immune target.
Current behaviour:
Glyph does not reset cd on immune targets.
Expected behaviour:
reset cd on immune targets.
Links:
https://wow.gamepedia.com/Glyph_of_Resilient_Grip
![image](https://user-images.githubusercontent.com/58305537/70466564-68db3d00-1a91-11ea-8a88-2ed26fa1cc2c.png)

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
