### ISSUE TITLE
Lunar shower

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#80]
Description:
This talent allows moonfire to generate both eclipses 8 energy at a time.

Current behaviour:
Moonfire generates solar energy, but does not generate lunar energy after solar eclipse has faded.

Expected behaviour:
8 energy, Identical to whatever system starsurge uses, as starsurge does it properly right now.
![image](https://user-images.githubusercontent.com/58305537/70473034-397efd00-1a9e-11ea-8119-9a3d2b9f7e33.png)

Links:
(Shown in first 30s of 2011 retail video)
https://wowwiki.fandom.com/wiki/Lunar_Shower
https://www.youtube.com/watch?v=tOGhgO_0gCk

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
