### ISSUE TITLE
Potion Stacking

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#81]
Description:
On-Use consumables such as potion of the tol'vir and golemblood potion.

Current behaviour:
![image](https://user-images.githubusercontent.com/58305537/70480495-da28e900-1aad-11ea-8eb7-67ac57823c58.png)

Expected behaviour:
Consumable potions should prevent others from being stackable.

Links:

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
