### ISSUE TITLE
Guardian of ancient kings

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#82]
Description:
Paladin pet that follows and assists a retribution paladin.

Current behaviour:
1. The pet can be targeted for attacks, and is easily killed.
2. The pet does not attack any targets outside of melee range of the paladin.

Expected behaviour:
The pet should not be targetable.
The pet should act as an "assist" pet.

The tooltip says "or until killed", so he may be vulnerable to aoe damage.

Links:
![image](https://user-images.githubusercontent.com/58305537/70481154-b9619300-1aaf-11ea-8dc4-0b32bbdc0239.png)

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
