### ISSUE TITLE
Holy Wrath (DR Trigger)

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#83]
Description:
Spread x damage across everyone in an area around you.

Current behaviour:
Currently triggers the DR on hammer of justice without stunning targets.

Expected behaviour:
Holy wrath should only trigger the hard stun DR if it stuns the target.

Links:

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by PN-Cryptid** [comment]
Fixed in the past months.
