### ISSUE TITLE
Raid World Markers

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#84]
Description:
World markers do not seem to work when outside of an instance.
Current behaviour:
World markers do not seem to work when outside of an instance.
I also noticed that world marker placement also triggers a GCD, not sure if that's right.
Expected behaviour:
World markers should be visible to raid members when outside of instances.
Links:
![image](https://user-images.githubusercontent.com/58305537/70545109-12c2d400-1b3b-11ea-87fa-81d272d427a4.png)

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
https://www.youtube.com/watch?v=cmveO_DNevc

moved to: https://forum.projectnelth.com/bugtracker/raid-world-markers-do-not-seem-to-work-when-outside-of-an-instance-r74/
