### ISSUE TITLE
Two-Hand Specialization (warrior)

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#85]
Spell ID: 12712

Issue:
When learned, Two-Hand specialization increases by an inconsistent amount, but always over 12%.

(Grey Sword) - The calculation to the left is the coefficient of the minimum damage. To the right, maximum coefficient.

![image](https://user-images.githubusercontent.com/58305537/70555600-5a525b80-1b4d-11ea-939d-993a36a1eaa2.png)

(Gurthalak HC)
![image](https://user-images.githubusercontent.com/58305537/70555810-c7fe8780-1b4d-11ea-8fa6-a1703a72cde7.png)

These tests were done with the passive isolated.
This was done by testing  in defensive stance and by learning only Blitz (1/2) to add the arms passive.

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
values are calculated on average damage. ((min dmg 2h spec+max dmg 2h spec)/2) / (min dmg no spec+max dmg no spec)/2 = 1.1200327.
