### ISSUE TITLE
Heroic Leap

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#88]
Description:
Leap to designated target, causing x damage in x range.
Current behaviour:
Heroic leap is unaffected by battle stance damage coefficient.
Expected behaviour:
Heroic leap's damage is part of "all damage" and should be increased by a 1.05 coefficient with battle stance.
Links:

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
