### ISSUE TITLE
Cleave

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#89]
Description:
Attack target and 1 nearby target for x damage.
Current behaviour:
Attack target and 1 nearby target for x damage.
-Does not scale with battle stance
Expected behaviour:
Attack target and 1 nearby target for x damage.
(Scaled with battle stance)
Links:

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
