### ISSUE TITLE
Murder Was The Case That They Gave Me

### ISSUE THREAD

**Issue by Snackhrot** [ProjectNelth/BugTracker#9]
Description: Quest is working only 75%

Current behaviour: The npcs "Transient" are not doing what they're supposed to. When you speak with them you get 2 options - to ask them or to give them money. Right now if you ask them they dont do anything. If you give them money, they take the money and do to anything.

Expected behaviour: They are supposed to either contribute to the clues that are needed in the quest when speaking/giving them money or they'd attack you.

Links: https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me

**Comment by iRadioactive** [comment]
I was able to complete the quest by only asking, and I was also able to complete the quest by only giving money.

Quest is very messy tho and needs some work.
Will get back to this.
