### ISSUE TITLE
Field Dressing

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#90]
Description:
Increase all healing received by 6%, and the effectiveness of your self-healing abilities by an additional 20%.

Current behaviour:
1. Increases the effectiveness of your self-healing abilities by 20%.
![image](https://user-images.githubusercontent.com/58305537/70562969-61806600-1b5b-11ea-8ca9-8b27d951f11e.png)

Enraged regeneration increases from 30% to 36% of health after adding this talent. 36/30 = 1.2, meaning only the 20% self healing is working.Victory Rush healing is increased from 20% to 24% of health after adding this talent. This also confirms the self healing is only increased by the 20%.

2. Bloothirst healing is not increased by this talent.

Expected behaviour:
1. As worded, the "additional" healing implies the two healing coefficients stack.
2. Bloodthirst or "bloody healing" should be buffed by this talent.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
