### ISSUE TITLE
Slaughter: Slam + Mortal Strike scaling

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#91]
Description:
Increases damage of execute, overpower, slam, mortal strike.

Current behaviour:
slam and mortal strike are scaled down slightly in their benefit from slaughter stacks.
![image](https://user-images.githubusercontent.com/58305537/70567271-9bee0100-1b63-11ea-823c-152cefe6ae25.png)

Expected behaviour:
All coefficients should equal 1.3 (0.1 additional per stack)

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
