### ISSUE TITLE
War Academy - Victory Rush

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#92]
Description:
Increases the damage of Victory Rush by 5, 10, 15%.
Current behaviour:
With 1 point in war academy, victory rush's damage is increased by 20%.
Expected behaviour:
Increases the damage of Victory Rush by 5, 10, 15%.
Links:
![image](https://user-images.githubusercontent.com/58305537/70567628-4ebe5f00-1b64-11ea-942c-3412c66d2027.png)

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.

**Comment by therealsmf** [comment]
every point seems to give a static 106.596% increase over 0/3.
