### ISSUE TITLE
Dragonmaw portal to orgrimmar

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#93]
Description:
The portal in twilight highlands right behind you if you teleport to TH from orgrimmar.
Current behaviour:
The portal to orgrimmar in twilight highlands is targetable and does not work.
Expected behaviour:
The portal should operate and not be targetable.

Links:
![image](https://user-images.githubusercontent.com/58305537/70580373-81c31b80-1b81-11ea-83cc-2a11e1018e4c.png)

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.
