### ISSUE TITLE
Fel Intelligence

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#94]
Description:
Buff from felhunter.

Current behaviour:
1. The pet cast bar icon will not switch to an "active aura" image when the aura is active.
2. Because the bar will never switch to "active aura" even though the aura is active, the pet will rapidly re-cast the aura if auto-cast is selected.

Expected behaviour:
The pet spell bar should show an active aura when fel intelligence is active.
Links:
![image](https://user-images.githubusercontent.com/58305537/70587825-f8b7de80-1b98-11ea-8ed2-e57e731b3110.png)

**Comment by cryptid123** [comment]
Based off of examined behavior, not a possibly bugged tooltip.

**Comment by therealsmf** [comment]
also true for every pet aura, not just fel int.

**Comment by PN-Cryptid** [comment]
Part 2 has been fixed for a while. part1 is still a visual issue.

**Comment by therealsmf** [comment]
moved and merged with https://forum.projectnelth.com/bugtracker/pet-spells-autocasts-r75/
