### ISSUE TITLE
[NPC][Quest]

### ISSUE THREAD

**Issue by Akka3223** [ProjectNelth/BugTracker#96]
Description: Random question mark above the npc head

Current behaviour: Question mark above, can't take anything.

Expected behaviour: I don't know which quest is it.

Links: https://gyazo.com/aed12f734e2d8cf40c6e859c9650a801

Database NPC Flag problem probably :) If youre using trinitycore you can try this fix : 
UPDATE `creature_template` SET `npcflag`=2 WHERE `entry`=52408;

**Comment by therealsmf** [comment]
should be reported in the big zone reports on the questing spreadsheet. if the issue still exists after changes, reopen on the forum :)
