### ISSUE TITLE
Balance of Power

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#97]
Description:
Increase nature and arcane damage by (1-2)%, and increase spell hit rating by (50-100)% of spirit.
Current behaviour:
Does not increase spell damage at all.
Expected behaviour:
Should give a 2% damage bonus to arcane and nature spells.

Links:
![image](https://user-images.githubusercontent.com/58305537/70636266-394c4200-1c03-11ea-8550-ecacdb9b73fb.png)

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
