### ISSUE TITLE
Genesis

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#98]
Description:
Increase the duration of swarm and moonfire by 2 seconds per talent point
Current behaviour:
1. First two talent points seem to be close to correct, but are not exactly 2 seconds.
2. The third talent point gives a double benefit increasing the duration by 8 seconds instead of 6 seconds.
3. The overall damage of the moonfire DOT is spread across the extra time with weaker ticks, rather than adding ticks.

Expected behaviour:
1+2: Increase duration of swarm and moonfire by 2 seconds per talent point.
3. Must increase overall damage of moonfire dots by adding ticks, and keeping the tick damage constant.

Links:
Issues 1+2:
![image](https://user-images.githubusercontent.com/58305537/70643659-669eed00-1c0f-11ea-92d8-3e58f375edbb.png)

Issue 3:
![image](https://user-images.githubusercontent.com/58305537/70643482-145dcc00-1c0f-11ea-9e48-caa89e507708.png)

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
