### ISSUE TITLE
Moonkin Form

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#99]
Description:
Increase spell damage by 10%.
Decrease damage taken by 15%.
Current behaviour:
zero damage increase to spells with moonkin form.
![image](https://user-images.githubusercontent.com/58305537/70644250-a61a0900-1c10-11ea-838b-d2eb00459ec4.png)

Expected behaviour:
10% damage increase to all spells.

**Comment by cryptid123** [comment]
This report was based off tooltip examination, not behavior.
Behavior should be checked.
